// Mocks generated by Mockito 5.3.2 from annotations
// in wmd/test/features/add_assets/custodian_bank_auth/data/repositories/custodian_bank_auth_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:wmd/features/add_assets/custodian_bank_auth/data/data_sources/custodian_bank_auth_remote_datasource.dart'
    as _i4;
import 'package:wmd/features/add_assets/custodian_bank_auth/data/models/custodian_bank_response.dart'
    as _i6;
import 'package:wmd/features/add_assets/custodian_bank_auth/data/models/delete_custodian_bank_status_params.dart'
    as _i11;
import 'package:wmd/features/add_assets/custodian_bank_auth/data/models/get_custodian_bank_list_params.dart'
    as _i7;
import 'package:wmd/features/add_assets/custodian_bank_auth/data/models/get_custodian_bank_status_params.dart'
    as _i10;
import 'package:wmd/features/add_assets/custodian_bank_auth/data/models/get_custodian_bank_status_response.dart'
    as _i3;
import 'package:wmd/features/add_assets/custodian_bank_auth/data/models/post_custodian_bank_status_params.dart'
    as _i8;
import 'package:wmd/features/add_assets/custodian_bank_auth/data/models/post_custodian_bank_status_response.dart'
    as _i2;
import 'package:wmd/features/add_assets/custodian_bank_auth/data/models/put_custodian_bank_status_params.dart'
    as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePostCustodianBankStatusResponse_0 extends _i1.SmartFake
    implements _i2.PostCustodianBankStatusResponse {
  _FakePostCustodianBankStatusResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetCustodianBankStatusResponse_1 extends _i1.SmartFake
    implements _i3.GetCustodianBankStatusResponse {
  _FakeGetCustodianBankStatusResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CustodianBankAuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCustodianBankAuthRemoteDataSource extends _i1.Mock
    implements _i4.CustodianBankAuthRemoteDataSource {
  MockCustodianBankAuthRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i6.CustodianBankResponse>> getCustodianBankList(
          _i7.GetCustodianBankListParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCustodianBankList,
          [params],
        ),
        returnValue: _i5.Future<List<_i6.CustodianBankResponse>>.value(
            <_i6.CustodianBankResponse>[]),
      ) as _i5.Future<List<_i6.CustodianBankResponse>>);
  @override
  _i5.Future<_i2.PostCustodianBankStatusResponse> postCustodianBankStatus(
          _i8.PostCustodianBankStatusParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #postCustodianBankStatus,
          [params],
        ),
        returnValue: _i5.Future<_i2.PostCustodianBankStatusResponse>.value(
            _FakePostCustodianBankStatusResponse_0(
          this,
          Invocation.method(
            #postCustodianBankStatus,
            [params],
          ),
        )),
      ) as _i5.Future<_i2.PostCustodianBankStatusResponse>);
  @override
  _i5.Future<_i2.PostCustodianBankStatusResponse> putCustodianBankStatus(
          _i9.PutCustodianBankStatusParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #putCustodianBankStatus,
          [params],
        ),
        returnValue: _i5.Future<_i2.PostCustodianBankStatusResponse>.value(
            _FakePostCustodianBankStatusResponse_0(
          this,
          Invocation.method(
            #putCustodianBankStatus,
            [params],
          ),
        )),
      ) as _i5.Future<_i2.PostCustodianBankStatusResponse>);
  @override
  _i5.Future<_i3.GetCustodianBankStatusResponse> getCustodianBankStatus(
          _i10.GetCustodianBankStatusParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCustodianBankStatus,
          [params],
        ),
        returnValue: _i5.Future<_i3.GetCustodianBankStatusResponse>.value(
            _FakeGetCustodianBankStatusResponse_1(
          this,
          Invocation.method(
            #getCustodianBankStatus,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.GetCustodianBankStatusResponse>);
  @override
  _i5.Future<void> deleteCustodianBankStatus(
          _i11.DeleteCustodianBankStatusParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCustodianBankStatus,
          [params],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<List<_i3.GetCustodianBankStatusResponse>> getCustodianStatusList(
          _i7.GetCustodianBankListParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCustodianStatusList,
          [params],
        ),
        returnValue: _i5.Future<List<_i3.GetCustodianBankStatusResponse>>.value(
            <_i3.GetCustodianBankStatusResponse>[]),
      ) as _i5.Future<List<_i3.GetCustodianBankStatusResponse>>);
}
