// Mocks generated by Mockito 5.3.2 from annotations
// in wmd/test/features/settings/linked_accounts/presentation/manager/linked_accounts_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:wmd/core/error_and_success/failures.dart' as _i6;
import 'package:wmd/core/error_and_success/succeses.dart' as _i10;
import 'package:wmd/features/add_assets/custodian_bank_auth/data/models/delete_custodian_bank_status_params.dart'
    as _i11;
import 'package:wmd/features/settings/linked_accounts/data/models/get_linked_accounts_params.dart'
    as _i8;
import 'package:wmd/features/settings/linked_accounts/domain/entities/get_linked_accounts_entity.dart'
    as _i7;
import 'package:wmd/features/settings/linked_accounts/domain/repositories/linked_accounts_repository.dart'
    as _i2;
import 'package:wmd/features/settings/linked_accounts/domain/use_cases/delete_linked_accounts_usecase.dart'
    as _i9;
import 'package:wmd/features/settings/linked_accounts/domain/use_cases/get_linked_accounts_usecase.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLinkedAccountsRepository_0 extends _i1.SmartFake
    implements _i2.LinkedAccountsRepository {
  _FakeLinkedAccountsRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetLinkedAccountsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetLinkedAccountsUseCase extends _i1.Mock
    implements _i4.GetLinkedAccountsUseCase {
  MockGetLinkedAccountsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LinkedAccountsRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeLinkedAccountsRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.LinkedAccountsRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.GetLinkedAccountsEntity>>> call(
          _i8.GetLinkedAccountsParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<
                _i3.Either<_i6.Failure,
                    List<_i7.GetLinkedAccountsEntity>>>.value(
            _FakeEither_1<_i6.Failure, List<_i7.GetLinkedAccountsEntity>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5
          .Future<_i3.Either<_i6.Failure, List<_i7.GetLinkedAccountsEntity>>>);
}

/// A class which mocks [DeleteLinkedAccountsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteLinkedAccountsUseCase extends _i1.Mock
    implements _i9.DeleteLinkedAccountsUseCase {
  MockDeleteLinkedAccountsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LinkedAccountsRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeLinkedAccountsRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.LinkedAccountsRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, _i10.AppSuccess>> call(
          _i11.DeleteCustodianBankStatusParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i10.AppSuccess>>.value(
            _FakeEither_1<_i6.Failure, _i10.AppSuccess>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i10.AppSuccess>>);
}
