// Mocks generated by Mockito 5.3.2 from annotations
// in wmd/test/features/force_update/presentation/manager/force_update_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dartz/dartz.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:package_info_plus/package_info_plus.dart' as _i3;
import 'package:wmd/core/domain/usecases/usercase.dart' as _i9;
import 'package:wmd/core/error_and_success/failures.dart' as _i7;
import 'package:wmd/features/force_update/domain/entities/get_force_update_entity.dart'
    as _i8;
import 'package:wmd/features/force_update/domain/repositories/force_update_repository.dart'
    as _i2;
import 'package:wmd/features/force_update/domain/use_cases/get_force_update_usecase.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeForceUpdateRepository_0 extends _i1.SmartFake
    implements _i2.ForceUpdateRepository {
  _FakeForceUpdateRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePackageInfo_1 extends _i1.SmartFake implements _i3.PackageInfo {
  _FakePackageInfo_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_2<L, R> extends _i1.SmartFake implements _i4.Either<L, R> {
  _FakeEither_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetForceUpdateUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetForceUpdateUseCase extends _i1.Mock
    implements _i5.GetForceUpdateUseCase {
  MockGetForceUpdateUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ForceUpdateRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeForceUpdateRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ForceUpdateRepository);
  @override
  _i3.PackageInfo get packageInfo => (super.noSuchMethod(
        Invocation.getter(#packageInfo),
        returnValue: _FakePackageInfo_1(
          this,
          Invocation.getter(#packageInfo),
        ),
      ) as _i3.PackageInfo);
  @override
  _i6.Future<_i4.Either<_i7.Failure, _i8.GetForceUpdateEntity>> call(
          _i9.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i6.Future<_i4.Either<_i7.Failure, _i8.GetForceUpdateEntity>>.value(
                _FakeEither_2<_i7.Failure, _i8.GetForceUpdateEntity>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i6.Future<_i4.Either<_i7.Failure, _i8.GetForceUpdateEntity>>);
}
