// Mocks generated by Mockito 5.3.2 from annotations
// in wmd/test/features/assets_overview/currency_chart/data/repositories/currency_chart_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:wmd/core/error_and_success/failures.dart' as _i8;
import 'package:wmd/features/assets_overview/currency_chart/data/data_sources/currency_chart_remote_datasource.dart'
    as _i3;
import 'package:wmd/features/assets_overview/currency_chart/data/models/get_currency_params.dart'
    as _i6;
import 'package:wmd/features/assets_overview/currency_chart/data/models/get_currency_response.dart'
    as _i5;
import 'package:wmd/features/assets_overview/currency_chart/domain/entities/get_currency_entity.dart'
    as _i9;
import 'package:wmd/features/assets_overview/currency_chart/domain/repositories/currency_chart_repository.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CurrencyChartRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCurrencyChartRemoteDataSource extends _i1.Mock
    implements _i3.CurrencyChartRemoteDataSource {
  MockCurrencyChartRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.GetCurrencyResponse>> getCurrency(
          _i6.GetCurrencyParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrency,
          [params],
        ),
        returnValue: _i4.Future<List<_i5.GetCurrencyResponse>>.value(
            <_i5.GetCurrencyResponse>[]),
      ) as _i4.Future<List<_i5.GetCurrencyResponse>>);
}

/// A class which mocks [CurrencyChartRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCurrencyChartRepository extends _i1.Mock
    implements _i7.CurrencyChartRepository {
  MockCurrencyChartRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i8.Failure, List<_i9.GetCurrencyEntity>>> getCurrency(
          _i6.GetCurrencyParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrency,
          [params],
        ),
        returnValue: _i4.Future<
                _i2.Either<_i8.Failure, List<_i9.GetCurrencyEntity>>>.value(
            _FakeEither_0<_i8.Failure, List<_i9.GetCurrencyEntity>>(
          this,
          Invocation.method(
            #getCurrency,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i8.Failure, List<_i9.GetCurrencyEntity>>>);
}
