// Mocks generated by Mockito 5.3.2 from annotations
// in wmd/test/features/dashboard/main_dashboard/data/repositories/main_dashboard_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:wmd/core/error_and_success/failures.dart' as _i8;
import 'package:wmd/features/dashboard/main_dashbaord/data/data_sources/main_dashboard_remote_data_source.dart'
    as _i4;
import 'package:wmd/features/dashboard/main_dashbaord/data/models/net_worth_params.dart'
    as _i6;
import 'package:wmd/features/dashboard/main_dashbaord/data/models/net_worth_response_obj.dart'
    as _i2;
import 'package:wmd/features/dashboard/main_dashbaord/domain/repositories/main_dashboard_repository.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNetWorthResponseObj_0 extends _i1.SmartFake
    implements _i2.NetWorthResponseObj {
  _FakeNetWorthResponseObj_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MainDashboardRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMainDashboardRemoteDataSource extends _i1.Mock
    implements _i4.MainDashboardRemoteDataSource {
  MockMainDashboardRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.NetWorthResponseObj> userNetWorth(
          _i6.NetWorthParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #userNetWorth,
          [params],
        ),
        returnValue: _i5.Future<_i2.NetWorthResponseObj>.value(
            _FakeNetWorthResponseObj_0(
          this,
          Invocation.method(
            #userNetWorth,
            [params],
          ),
        )),
      ) as _i5.Future<_i2.NetWorthResponseObj>);
}

/// A class which mocks [MainDashboardRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMainDashboardRepository extends _i1.Mock
    implements _i7.MainDashboardRepository {
  MockMainDashboardRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Either<_i8.Failure, _i2.NetWorthResponseObj>> userNetWorth(
          _i6.NetWorthParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #userNetWorth,
          [params],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i8.Failure, _i2.NetWorthResponseObj>>.value(
                _FakeEither_1<_i8.Failure, _i2.NetWorthResponseObj>(
          this,
          Invocation.method(
            #userNetWorth,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i8.Failure, _i2.NetWorthResponseObj>>);
}
