// Mocks generated by Mockito 5.3.1 from annotations
// in wmd/test/features/help/faq/presentation/manager/faq_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:wmd/core/domain/usecases/usercase.dart' as _i8;
import 'package:wmd/core/error_and_success/failures.dart' as _i6;
import 'package:wmd/features/help/faq/data/models/faq.dart' as _i7;
import 'package:wmd/features/help/faq/domain/repositories/faq_repository.dart'
    as _i2;
import 'package:wmd/features/help/faq/domain/use_cases/get_faq_usecase.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFaqRepository_0 extends _i1.SmartFake implements _i2.FaqRepository {
  _FakeFaqRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetFaqUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetFaqUseCase extends _i1.Mock implements _i4.GetFaqUseCase {
  MockGetFaqUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FaqRepository get faqRepository => (super.noSuchMethod(
        Invocation.getter(#faqRepository),
        returnValue: _FakeFaqRepository_0(
          this,
          Invocation.getter(#faqRepository),
        ),
      ) as _i2.FaqRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.Faq>>> call(
          _i8.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, List<_i7.Faq>>>.value(
            _FakeEither_1<_i6.Failure, List<_i7.Faq>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.Faq>>>);
}
