class CountriesJson{
  static final json = {
    "iR".toLowerCase(): "Asia",
    "rU".toLowerCase(): "Asia",
    "aF".toLowerCase(): "Asia",
    "aM".toLowerCase(): "Asia",
    "aZ".toLowerCase(): "Asia",
    "bH".toLowerCase(): "Asia",
    "bD".toLowerCase(): "Asia",
    "bT".toLowerCase(): "Asia",
    "bN".toLowerCase(): "Asia",
    "kH".toLowerCase(): "Asia",
    "cN".toLowerCase(): "Asia",
    "cX".toLowerCase(): "Asia",
    "cC".toLowerCase(): "Asia",
    "iO".toLowerCase(): "Asia",
    "gE".toLowerCase(): "Asia",
    "hK".toLowerCase(): "Asia",
    "iN".toLowerCase(): "Asia",
    "iD".toLowerCase(): "Asia",
    "iQ".toLowerCase(): "Asia",
    "iL".toLowerCase(): "Asia",
    "jP".toLowerCase(): "Asia",
    "jO".toLowerCase(): "Asia",
    "kZ".toLowerCase(): "Asia",
    "kW".toLowerCase(): "Asia",
    "kG".toLowerCase(): "Asia",
    "lA".toLowerCase(): "Asia",
    "lB".toLowerCase(): "Asia",
    "mO".toLowerCase(): "Asia",
    "mY".toLowerCase(): "Asia",
    "mV".toLowerCase(): "Asia",
    "mN".toLowerCase(): "Asia",
    "mM".toLowerCase(): "Asia",
    "nP".toLowerCase(): "Asia",
    "kP".toLowerCase(): "Asia",
    "oM".toLowerCase(): "Asia",
    "pK".toLowerCase(): "Asia",
    "pS".toLowerCase(): "Asia",
    "pH".toLowerCase(): "Asia",
    "qA".toLowerCase(): "Asia",
    "sA".toLowerCase(): "Asia",
    "sG".toLowerCase(): "Asia",
    "kR".toLowerCase(): "Asia",
    "lK".toLowerCase(): "Asia",
    "sY".toLowerCase(): "Asia",
    "tW".toLowerCase(): "Asia",
    "tJ".toLowerCase(): "Asia",
    "tH".toLowerCase(): "Asia",
    "tR".toLowerCase(): "Asia",
    "tM".toLowerCase(): "Asia",
    "aE".toLowerCase(): "Asia",
    "uZ".toLowerCase(): "Asia",
    "vN".toLowerCase(): "Asia",
    "yE".toLowerCase(): "Asia",
    "fR".toLowerCase(): "Europe",
    "aT".toLowerCase(): "Europe",
    "bE".toLowerCase(): "Europe",
    "bG".toLowerCase(): "Europe",
    "hR".toLowerCase(): "Europe",
    "cY".toLowerCase(): "Europe",
    "cZ".toLowerCase(): "Europe",
    "aQ".toLowerCase(): "Europe",
    "aX".toLowerCase(): "Europe",
    "bA".toLowerCase(): "Europe",
    "bV".toLowerCase(): "Europe",
    "bY".toLowerCase(): "Europe",
    "cH".toLowerCase(): "Europe",
    "fO".toLowerCase(): "Europe",
    "gG".toLowerCase(): "Europe",
    "gI".toLowerCase(): "Europe",
    "gS".toLowerCase(): "Europe",
    "hM".toLowerCase(): "Europe",
    "iM".toLowerCase(): "Europe",
    "jE".toLowerCase(): "Europe",
    "mC".toLowerCase(): "Europe",
    "mE".toLowerCase(): "Europe",
    "mF".toLowerCase(): "Europe",
    "mK".toLowerCase(): "Europe",
    "nO".toLowerCase(): "Europe",
    "pN".toLowerCase(): "Europe",
    "pT".toLowerCase(): "Europe",
    "rS".toLowerCase(): "Europe",
    "sJ".toLowerCase(): "Europe",
    "sM".toLowerCase(): "Europe",
    "tF".toLowerCase(): "Europe",
    "uA".toLowerCase(): "Europe",
    "vA".toLowerCase(): "Europe",
    "xK".toLowerCase(): "Europe",
    "dK".toLowerCase(): "Europe",
    "eE".toLowerCase(): "Europe",
    "fI".toLowerCase(): "Europe",
    "dE".toLowerCase(): "Europe",
    "gR".toLowerCase(): "Europe",
    "hU".toLowerCase(): "Europe",
    "iE".toLowerCase(): "Europe",
    "iT".toLowerCase(): "Europe",
    "lV".toLowerCase(): "Europe",
    "lT".toLowerCase(): "Europe",
    "lU".toLowerCase(): "Europe",
    "mT".toLowerCase(): "Europe",
    "nL".toLowerCase(): "Europe",
    "pL".toLowerCase(): "Europe",
    "rO".toLowerCase(): "Europe",
    "sK".toLowerCase(): "Europe",
    "sI".toLowerCase(): "Europe",
    "eS".toLowerCase(): "Europe",
    "sE".toLowerCase(): "Europe",
    "gB".toLowerCase(): "Europe",
    "aD".toLowerCase(): "Europe",
    "aL".toLowerCase(): "Europe",
    "dZ".toLowerCase(): "Africa",
    "aO".toLowerCase(): "Africa",
    "sH".toLowerCase(): "Africa",
    "bJ".toLowerCase(): "Africa",
    "bW".toLowerCase(): "Africa",
    "bF".toLowerCase(): "Africa",
    "bI".toLowerCase(): "Africa",
    "cM".toLowerCase(): "Africa",
    "cV".toLowerCase(): "Africa",
    "cF".toLowerCase(): "Africa",
    "tD".toLowerCase(): "Africa",
    "kM".toLowerCase(): "Africa",
    "cG".toLowerCase(): "Africa",
    "cD".toLowerCase(): "Africa",
    "dJ".toLowerCase(): "Africa",
    "eG".toLowerCase(): "Africa",
    "nE".toLowerCase(): "Africa",
    "gQ".toLowerCase(): "Africa",
    "eR".toLowerCase(): "Africa",
    "sZ".toLowerCase(): "Africa",
    "eT".toLowerCase(): "Africa",
    "gA".toLowerCase(): "Africa",
    "gM".toLowerCase(): "Africa",
    "gH".toLowerCase(): "Africa",
    "gN".toLowerCase(): "Africa",
    "gW".toLowerCase(): "Africa",
    "cI".toLowerCase(): "Africa",
    "kE".toLowerCase(): "Africa",
    "lS".toLowerCase(): "Africa",
    "lR".toLowerCase(): "Africa",
    "lY".toLowerCase(): "Africa",
    "mG".toLowerCase(): "Africa",
    "mW".toLowerCase(): "Africa",
    "mL".toLowerCase(): "Africa",
    "mR".toLowerCase(): "Africa",
    "mU".toLowerCase(): "Africa",
    "yT".toLowerCase(): "Africa",
    "mA".toLowerCase(): "Africa",
    "mZ".toLowerCase(): "Africa",
    "nA".toLowerCase(): "Africa",
    "nG".toLowerCase(): "Africa",
    "sT".toLowerCase(): "Africa",
    "rE".toLowerCase(): "Africa",
    "rW".toLowerCase(): "Africa",
    "sN".toLowerCase(): "Africa",
    "sC".toLowerCase(): "Africa",
    "sL".toLowerCase(): "Africa",
    "sO".toLowerCase(): "Africa",
    "zA".toLowerCase(): "Africa",
    "sS".toLowerCase(): "Africa",
    "sD".toLowerCase(): "Africa",
    "tZ".toLowerCase(): "Africa",
    "tG".toLowerCase(): "Africa",
    "tN".toLowerCase(): "Africa",
    "uG".toLowerCase(): "Africa",
    "zM".toLowerCase(): "Africa",
    "zW".toLowerCase(): "Africa",
    "aI".toLowerCase(): "North America",
    "aG".toLowerCase(): "North America",
    "aW".toLowerCase(): "North America",
    "bB".toLowerCase(): "North America",
    "mD".toLowerCase(): "North America",
    "bZ".toLowerCase(): "North America",
    "bM".toLowerCase(): "North America",
    "bQ".toLowerCase(): "North America",
    "vG".toLowerCase(): "North America",
    "cA".toLowerCase(): "North America",
    "kY".toLowerCase(): "North America",
    "cR".toLowerCase(): "North America",
    "cU".toLowerCase(): "North America",
    "cW".toLowerCase(): "North America",
    "eH".toLowerCase(): "North America",
    "dM".toLowerCase(): "North America",
    "dO".toLowerCase(): "North America",
    "sV".toLowerCase(): "North America",
    "gL".toLowerCase(): "North America",
    "gD".toLowerCase(): "North America",
    "gP".toLowerCase(): "North America",
    "lI".toLowerCase(): "North America",
    "gT".toLowerCase(): "North America",
    "hT".toLowerCase(): "North America",
    "hN".toLowerCase(): "North America",
    "iS".toLowerCase(): "North America",
    "jM".toLowerCase(): "North America",
    "mQ".toLowerCase(): "North America",
    "mX".toLowerCase(): "North America",
    "mS".toLowerCase(): "North America",
    "aN".toLowerCase(): "North America",
    "nI".toLowerCase(): "North America",
    "pA".toLowerCase(): "North America",
    "pR".toLowerCase(): "North America",
    "bL".toLowerCase(): "North America",
    "kN".toLowerCase(): "North America",
    "lC".toLowerCase(): "North America",
    "mP".toLowerCase(): "North America",
    "pM".toLowerCase(): "North America",
    "vC".toLowerCase(): "North America",
    "sX".toLowerCase(): "North America",
    "bS".toLowerCase(): "North America",
    "tT".toLowerCase(): "North America",
    "tC".toLowerCase(): "North America",
    "uS".toLowerCase(): "North America",
    "vI".toLowerCase(): "North America",
    "aR".toLowerCase(): "South America",
    "bO".toLowerCase(): "South America",
    "bR".toLowerCase(): "South America",
    "cL".toLowerCase(): "South America",
    "cO".toLowerCase(): "South America",
    "eC".toLowerCase(): "South America",
    "fK".toLowerCase(): "South America",
    "gF".toLowerCase(): "South America",
    "gY".toLowerCase(): "South America",
    "pY".toLowerCase(): "South America",
    "pE".toLowerCase(): "South America",
    "sR".toLowerCase(): "South America",
    "uY".toLowerCase(): "South America",
    "vE".toLowerCase(): "South America",
    "aU".toLowerCase(): "Oceania",
    "aS".toLowerCase(): "Oceania",
    "nZ".toLowerCase(): "Oceania",
    "cK".toLowerCase(): "Oceania",
    "tL".toLowerCase(): "Oceania",
    "fM".toLowerCase(): "Oceania",
    "fJ".toLowerCase(): "Oceania",
    "pF".toLowerCase(): "Oceania",
    "gU".toLowerCase(): "Oceania",
    "kI".toLowerCase(): "Oceania",
    "mH".toLowerCase(): "Oceania",
    "uM".toLowerCase(): "Oceania",
    "nR".toLowerCase(): "Oceania",
    "nC".toLowerCase(): "Oceania",
    "nU".toLowerCase(): "Oceania",
    "nF".toLowerCase(): "Oceania",
    "pW".toLowerCase(): "Oceania",
    "pG".toLowerCase(): "Oceania",
    "wS".toLowerCase(): "Oceania",
    "sB".toLowerCase(): "Oceania",
    "tK".toLowerCase(): "Oceania",
    "tO".toLowerCase(): "Oceania",
    "tV".toLowerCase(): "Oceania",
    "vU".toLowerCase(): "Oceania",
    "wF".toLowerCase(): "Oceania",
  };
}