import 'dart:convert';

void main() {
  var myObj = {
    "auth:signup.page.title": "Join our Platform",
    "auth:signup.page.description": "Create mytfo account",
    "auth:signup.heading": "Create an account",
    "auth:signup.subHeading": "To better control your investments",
    "auth:signup.productDetails.one": "Combine your assets and investments in one secure platform.",
    "auth:signup.productDetails.two": "Monitor your net worth and the performance of your investments.",
    "auth:signup.productDetails.three": "Analyze your data and plan for your financial goals.",
    "auth:signup.text.aboutFamilyOffice": "About Petiole",
    "auth:signup.text.social": "or sign up with",
    "auth:signup.text.alreadyHaveAnAccount": "Already verified your email?",
    "auth:signup.input.email.placeholder": "Enter your email address",
    "auth:signup.input.password.placeholder": "Choose password",
    "auth:signup.input.validation.heading": "Your password must contain:",
    "auth:signup.input.validation.lowercase": "Lowercase letters (a-z)",
    "auth:signup.input.validation.uppercase": "Uppercase letters (A-Z)",
    "auth:signup.input.validation.numbers": "Numbers (0-9)",
    "auth:signup.input.validation.special": "Special characters (ex.!@#)",
    "auth:signup.input.validation.length": "At least 8 characters",
    "auth:signup.checkbox.label": "I have read, understand and agree to Petiole ",
    "auth:signup.checkbox.termsService": "Terms of Service",
    "auth:signup.button.submit": "Get Started",
    "auth:signup.button.join": "Join with your email address",
    "auth:signup.button.appleLogin": "Continue with Apple",
    "auth:signup.button.createAccount": "Create account",
    "auth:signup.link.login": "Log in",
    "auth:signup.toast.error.title": "An error occurred while processing your request. Try again or login if you already have an account.",
    "auth:signup.slides.0": "<0>Combine your assets <1>and investments in one secure platform.<\/1><\/0>",
    "auth:signup.slides.1": "<0>Monitor your net worth <1>and the performance of your investments.<\/1><\/0>",
    "auth:signup.slides.2": "<0>Analyze your data <1>and plan for your financial goals.<\/1><\/0>",
    "auth:signup.safeandsecure.title": "Safe and secure technology guaranteed.",
    "auth:signup.tos.title": "Terms of Use",
    "auth:signup.tos.content": "<0><1>Petiole Asset Management AG (“Petiole”) is an asset manager of collective assets, licensed and supervised by the Swiss Financial Market Supervisory Authority (FINMA).<\/1><1>The content of this website (“Website”) is provided by Petiole and is exclusively intended for persons domiciled in Switzerland. The Website may not be accessed by any user if and to the extent such access is illegal. By accessing this Website and the information and tools contained thereupon, you accept the present terms of use (“Terms of Use”). In case you do not consent to the Terms of Use, you may not access the Website or the information and tools contained thereupon. You understand that the Terms of Use as well as any information and or tools contained on this Website may be amended and\/or removed without prior notice.<\/1><1>The information contained on this Website – unless explicitly and separately indicated to you for specific sections of this Website – is for informational and advertising purposes only and does neither an offer of financial instruments nor a personalized recommendation to buy or sell any financial instruments unless explicitly indicated for specific sections of this Website. Such specific sections of this Website will indicate to you prior to you entering such sections the nature of the content and may require additional confirmations and\/or agreements from your part and may only be accessible by certain types of investors. Neither the receipt nor the distribution of information through this Website establishes a client relationship except for such sections of this Website where such client relationship may explicitly be established by signing an agreement between you and Petiole. In case of conflicts, the terms provided for or agreements entered into related to such specific sections prevail over the Terms of Use.<\/1><1>Past performance is not indicative of future results. As such, the value of financial instruments, and the income derived therefrom may change frequently, may fall as well as rise, and there is no guarantee that your initial investment in a financial instrument will be returned. We recommend consulting with a professional financial advisor prior to taking any investment or divestment decisions and duly consider the risks associated with a financial instrument. Petiole does not provide any legal or tax advice and we recommend consulting with your professional advisors on related considerations.<\/1><1>This Website may contain information or statements that are forward-looking based upon current expectations and projections about future events. Such forward-looking information or statements are based solely on Petiole’s current understanding, expectations, estimates, financial models and projections. Such information or statements are uncertain and involve the risks that assumptions, unpredicted or unconsidered events or other factors may lead to developments that may substantially deviate from Petiole’s expectations. These factors may include but are not limited to economic and business conditions and developments or the introduction or removal of relevant laws and regulations. You understand that Petiole has no obligation and will not amend or update any forward-looking information or statements contained on this Website upon the occurrence of developments that may impact such information or statements.<\/1><1>Certain information on the Website may be based on information obtained from third-party sources that Petiole considered to be reliable. However, Petiole does not give any representation or warranty on the correctness of the information contained on this Website, be it at the present or any future date. Also, this Website may contain links to websites operated by third parties and activating such links is at your own risk. The content of such websites has been prepared by the respective third party and Petiole does not give any representation or warranty on the correctness of the information contained on such third party websites. Links on this Website may also not be understood as endorsement or approval of the contents of such websites.<\/1><1>Any and all information and content contained on this Website is furnished on an as-is-basis and Petiole does not provide any warranty be it express or implied. Petiole does not – to the fullest extent permissible by applicable laws and regulations – assume any liability for any loss or damage of any kind arising, regardless whether such loss or damage is direct or indirect in nature, caused by the use of any content or information provided on this Website. Petiole does not warrant that the Website, its information or any tool contained thereupon will be available for you at any particular time or that any mistakes or errors are corrected at any specific point in time or at all or that the Website may be the subject of cyber attacks of any kind. The use of the Website is at your own risk.<\/1><1>The entire Website is subject to copyright and all rights are reserved. No permission is granted by Petiole to copy or otherwise reproduce any part of this Website, except for the purely private, intended use by a user. No permission or license is granted without Petiole’s written consent to use or copy Petiole’s logo, design or other intellectual property or to establish links to this Website.<\/1><1>Petiole is affiliated with the independent Ombudsman Office Finanzombudsstelle Schweiz (FINOS), Talstrasse 20, 8001 Zurich, Switzerland, which is officially recognized by the Swiss Federal Department of Finance. In case of any disputes about legal claims between our clients and Petiole, our clients can contact this Ombudsman Office anytime. Information about possible administrative costs in connection with mediation procedures can be found on the website of the Ombudsman Office: https:\/\/www.finos.ch or by email (info@finos.ch).<\/1><\/0>",
    "auth:signup.contactUs.heading": "Contact Us",
    "auth:signup.contactUs.subheading": "For further information, or inquiries about this User Agreement or Privacy Policy please contact:",
    "auth:signup.contactUs.email": "onboarding@tfoco.com",
    "auth:signup.contactUs.services": "Business support team",
    "auth:signup.modal.aboutTfo.heading": "Who is Petiole?",
    "auth:signup.modal.aboutTfo.text.first": "As a boutique asset manager, Petiole capitalizes on its expertise and international partners to build you a robust diversified portfolio, in exclusive private market opportunities, capable of outperforming public markets.",
    "auth:signup.modal.aboutTfo.text.second": "We are regulated in Switzerland (FINMA), USA (SEC), Hong Kong (SFC), and The Cayman Islands (CIMA).",
    "auth:signup.modal.aboutTfo.text.third": "Petiole is a boutique asset manager that provides qualified investors access to exclusive and diversified private market investment opportunities. Our clients benefit from tailored alternative solutions, a rigorous investment process and a dedicated team specialized in private market investments.",
    "auth:verify.page.title": "Verify email",
    "auth:verify.page.description": "For further information or inquiries about this User Agreement or Privacy Policy please contact:",
    "auth:verify.heading": "Verify your email address",
    "auth:verify.description": "<0>To verify your email, please click the link in the message we sent to <1>{{email}}<\/1><\/0>",
    "auth:verify.text.alreadyVerified": "Already verified your email?",
    "auth:verify.text.noEmailReceived": "Didn't receive an email?",
    "auth:verify.link.resend": "Resend",
    "auth:verify.link.login": "Login",
    "auth:verify.toast.success.title": "Email verification sent",
    "auth:verify.toast.success.description": "Check your email for your verification link",
    "auth:verify.toast.error.title": "Something went wrong.",
    "auth:verify.toast.error.description": "We are unable to resend your email verification.",
    "auth:verifyResponse.page.title": "Verify email",
    "auth:verifyResponse.page.description": "Verify your email address",
    "auth:verifyResponse.button.resend": "Resend email",
    "auth:verifyResponse.text.success.heading": "Email confirmed",
    "auth:verifyResponse.text.success.subheading": "Your email is confirmed, please click on continue below.",
    "auth:verifyResponse.text.error.heading": "Link Expired",
    "auth:verifyResponse.text.error.subheading": "To verify your email, please click “Resend email” to receive a new verification link.",
    "common:errors.required": "This field is required",
    "common:errors.email": "Enter a valid email",
    "common:button.cancel": "Cancel",
    "common:button.acceptAll": "Accept all",
    "common:button.continue": "Continue",
    "auth:login.page.title": "Login",
    "auth:login.page.description": "Sign in to your mytfo account",
    "auth:login.heading": "Welcome back!",
    "auth:login.subheading": "Login to The Family Office to continue.",
    "auth:login.text.noAccount": "Don't have an account?",
    "auth:login.text.social": "or login with",
    "auth:login.input.email.placeholder": "Email\/Username",
    "auth:login.input.password.placeholder": "Password",
    "auth:login.button.login": "Login",
    "auth:login.link.signup": "Sign up",
    "auth:login.link.forgotPassword": "Forgot password?",
    "auth:login.toast.error.title": "Invalid email or password. Please try again.",
    "auth:forgot.page.title": "Reset Password",
    "auth:forgot.page.description": "To enter the email to receive new password email",
    "auth:forgot.heading": "Forgot your password?",
    "auth:forgot.subheading": "Please enter the email address that you registered with, and we'll send you a link to reset your password",
    "auth:forgot.input.email.placeholder": "Email",
    "auth:forgot.input.email.label": "Email",
    "auth:forgot.button.send": "Send",
    "auth:forgot.link.backToLogin": "Back to Login",
    "auth:forgot.link.resend": "Resend",
    "auth:forgot.link.resendIn": "Resend in",
    "auth:forgot.emailSentSuccess.heading": "Check your email",
    "auth:forgot.emailSentSuccess.subheading": "<0>We have sent a message to <1>{{email}}<\/1> with instructions to reset your password.<\/0>",
    "auth:forgot.text.didNotReceiveEmail": "Didn’t receive an email?",
    "auth:forgot.toast.success.title": "Email Sent",
    "auth:forgot.toast.error.title": "Email could not be sent",
    "auth:change.page.title": "Change Password",
    "auth:change.page.description": "To enter the new password",
    "auth:change.heading": "Choose a new password",
    "auth:change.subheading": "Please enter your new password below",
    "auth:change.input.password.placeholder": "Password",
    "auth:change.input.password.label": "Password",
    "auth:change.input.confirmPassword.placeholder": "Confirm Password",
    "auth:change.input.confirmPassword.label": "Confirm Password",
    "auth:change.button.changePassword": "Update Password",
    "auth:change.button.passwordUpdatedGoToLogin": "Go to Login",
    "auth:change.button.backToLogin": "Back to login",
    "auth:change.validation.heading": "Your password must contain:",
    "auth:change.validation.lowercase": "Lowercase letters (a-z)",
    "auth:change.validation.uppercase": "Uppercase letters (A-Z)",
    "auth:change.validation.numbers": "Numbers (0-9)",
    "auth:change.validation.special": "Special characters (ex.!@#)",
    "auth:change.validation.length": "At least 8 characters",
    "auth:change.validation.mismatch": "Passwords do not match",
    "auth:change.validation.isValidPass": "At least 3 of the following:",
    "auth:change.passwordUpdatedSuccess.heading": "Password Updated",
    "auth:change.passwordUpdatedSuccess.subheading": "Your password has been changed successfully.",
    "auth:change.linkExpired.heading": "Link Expired",
    "auth:change.linkExpired.subheading": "To reset your password, return to the login page and select \"Forgot password\" to receive a password reset email.",
    "auth:change.toast.success.title": "Password changed.",
    "auth:change.toast.error.title": "Password could not be changed.",
    "common:button.getStarted": "Get Started",
    "common:formExitModal.title": "Are you sure you want to leave this page?",
    "common:formExitModal.description": "Please note that if you exit this form, we will not be able save any data.",
    "common:formExitModal.buttons.back": "Back to form",
    "common:formExitModal.buttons.exit": "Exit Form",
    "common:formSuccessModal.title": "{{assetType}} is successfully added to wealth overview",
    "common:formSuccessModal.acquiredCost": "Acquired Cost",
    "common:formSuccessModal.netWorth": "Net Worth",
    "common:formSuccessModal.marketvalue": "Market value",
    "common:formSuccessModal.buttons.addAsset": "Add Another Asset",
    "common:formSuccessModal.buttons.viewAsset": "View Asset Details",
    "common:formSuccessModal.buttons.addLiability": "Add Another Liability",
    "common:formSuccessModal.buttons.viewLiability": "View Liability Details",
    "common:formSuccessModal.acceptAll": "Accept All",
    "common:formSuccessModal.continue": "Continue",
    "common:formSuccessModal.getStarted": "Get Started",
    "home:page.title": "Join our Platform",
    "home:page.description": "Create mytfo account",
    "home:emptyStateDashboard.title": "Combine Your Assets With Ease",
    "home:emptyStateDashboard.subtitle": "To better monitor the performance of your investments, analyze your data, and plan for your financial goals",
    "home:emptyStateDashboard.addAssetsSteps.assetClass": "We support multiple asset classes and currencies.",
    "home:emptyStateDashboard.addAssetsSteps.connectInstitutionsIcon": "We connect you to your financial institutions to avoid the hassle of manual updates.",
    "home:emptyStateDashboard.addAssetsSteps.highestSecurityIcon": "We use high security encryption to guarantee the safety of your data.",
    "assetLiabilityForms:page.title": "Add {{assetName}}",
    "assetLiabilityForms:page.description": "Add {{assetName}}",
    "assetLiabilityForms:heading.bankAccount": "Add bank account",
    "assetLiabilityForms:heading.listedAssets": "Add listed asset details",
    "assetLiabilityForms:heading.privateEquity": "Add private equity",
    "assetLiabilityForms:heading.privateDebt": "Add private debt",
    "assetLiabilityForms:assets.bankAccount": "Bank Account",
    "assetLiabilityForms:assets.listedAssets": "Listed Assets",
    "assetLiabilityForms:assets.privateEquity": "Private Equity",
    "assetLiabilityForms:assets.privateDebt": "Private Debt",
    "assetLiabilityForms:subHeading.bankAccount": "Current account, savings account and term deposit accounts.",
    "assetLiabilityForms:subHeading.listedAssets": "Investments made in stocks, ETFs, bonds and mutual funds.",
    "assetLiabilityForms:subHeading.privateEquity": "Investment in an entity that is not publicly listed.",
    "assetLiabilityForms:subHeading.privateDebt": "Asset defined by non-bank lending where debt is not issued or traded on the public markets",
    "assetLiabilityForms:forms.bankAccount.title": "Fill in your cash details",
    "assetLiabilityForms:forms.bankAccount.inputFields.bankName.label": "Bank name",
    "assetLiabilityForms:forms.bankAccount.inputFields.bankName.placeholder": "Your bank name",
    "assetLiabilityForms:forms.bankAccount.inputFields.bankName.errorMessage": "Please enter a bank name",
    "assetLiabilityForms:forms.bankAccount.inputFields.description.label": "Description",
    "assetLiabilityForms:forms.bankAccount.inputFields.description.placeholder": "A nickname you give to your account",
    "assetLiabilityForms:forms.bankAccount.inputFields.description.errorMessage": "Please enter description",
    "assetLiabilityForms:forms.bankAccount.inputFields.country.label": "Country",
    "assetLiabilityForms:forms.bankAccount.inputFields.country.placeholder": "Type or select a country",
    "assetLiabilityForms:forms.bankAccount.inputFields.country.errorMessage": "Please select country",
    "assetLiabilityForms:forms.bankAccount.inputFields.accountType.label": "Account type",
    "assetLiabilityForms:forms.bankAccount.inputFields.accountType.placeholder": "Type or select an account type",
    "assetLiabilityForms:forms.bankAccount.inputFields.accountType.errorMessage": "Please select account type",
    "assetLiabilityForms:forms.bankAccount.inputFields.accountType.options.savingAccount": "Saving Account",
    "assetLiabilityForms:forms.bankAccount.inputFields.accountType.options.currentAccount": "Current Account",
    "assetLiabilityForms:forms.bankAccount.inputFields.accountType.options.termDeposit": "Term Deposit",
    "assetLiabilityForms:forms.bankAccount.inputFields.currency.label": "Currency",
    "assetLiabilityForms:forms.bankAccount.inputFields.currency.placeholder": "Type or select an currency",
    "assetLiabilityForms:forms.bankAccount.inputFields.currency.errorMessage": "Please select currency",
    "assetLiabilityForms:forms.bankAccount.inputFields.balance.label": "Current Balance",
    "assetLiabilityForms:forms.bankAccount.inputFields.balance.placeholder": "000000",
    "assetLiabilityForms:forms.bankAccount.inputFields.balance.errorMessage": "Please enter balance amount",
    "assetLiabilityForms:forms.bankAccount.inputFields.ownership.label": "Ownership",
    "assetLiabilityForms:forms.bankAccount.inputFields.ownership.placeholder": "Ownership %",
    "assetLiabilityForms:forms.bankAccount.inputFields.ownership.errorMessage.minimum": "Minimum is 0.1%",
    "assetLiabilityForms:forms.bankAccount.inputFields.ownership.errorMessage.maximum": "Maximum is 100%",
    "assetLiabilityForms:forms.bankAccount.inputFields.ownership.errorMessage.error": "Please enter ownership percentage",
    "assetLiabilityForms:forms.bankAccount.inputFields.ownership.tooltip": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    "assetLiabilityForms:forms.bankAccount.inputFields.principal.label": "Principal (original deposit amount)",
    "assetLiabilityForms:forms.bankAccount.inputFields.principal.placeholder": "Enter principal amount",
    "assetLiabilityForms:forms.bankAccount.inputFields.principal.errorMessage": "Please enter principal amount",
    "assetLiabilityForms:forms.bankAccount.inputFields.principal.tooltip": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    "assetLiabilityForms:forms.bankAccount.inputFields.rate.label": "Rate (optional)",
    "assetLiabilityForms:forms.bankAccount.inputFields.rate.placeholder": "Enter rate",
    "assetLiabilityForms:forms.bankAccount.inputFields.rate.tooltip": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    "assetLiabilityForms:forms.bankAccount.inputFields.rate.errorMessage.minimum": "Minimum is 0.1%",
    "assetLiabilityForms:forms.bankAccount.inputFields.rate.errorMessage.maximum": "Maximum is 100%",
    "assetLiabilityForms:forms.bankAccount.inputFields.startDate.label": "Start date",
    "assetLiabilityForms:forms.bankAccount.inputFields.startDate.placeholder": "DD\/MM\/YYYY",
    "assetLiabilityForms:forms.bankAccount.inputFields.startDate.errorMessage": "Please selct start date",
    "assetLiabilityForms:forms.bankAccount.inputFields.startDate.tooltip": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    "assetLiabilityForms:forms.bankAccount.inputFields.tenure.label": "Tenure",
    "assetLiabilityForms:forms.bankAccount.inputFields.tenure.tooltip": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    "assetLiabilityForms:forms.bankAccount.inputFields.tenureYears.label": "Years",
    "assetLiabilityForms:forms.bankAccount.inputFields.tenureYears.placeholder": "YY",
    "assetLiabilityForms:forms.bankAccount.inputFields.tenureYears.errorMessage.minimum": "Minimum is 0",
    "assetLiabilityForms:forms.bankAccount.inputFields.tenureYears.errorMessage.maximum": "Minimum is 9999",
    "assetLiabilityForms:forms.bankAccount.inputFields.tenureMonths.label": "Months",
    "assetLiabilityForms:forms.bankAccount.inputFields.tenureMonths.placeholder": "MM",
    "assetLiabilityForms:forms.bankAccount.inputFields.tenureMonths.errorMessage.minimum": "Minimum is 0",
    "assetLiabilityForms:forms.bankAccount.inputFields.tenureMonths.errorMessage.maximum": "Maximum is 12",
    "assetLiabilityForms:forms.bankAccount.inputFields.tenureDays.label": "Days",
    "assetLiabilityForms:forms.bankAccount.inputFields.tenureDays.placeholder": "DD",
    "assetLiabilityForms:forms.bankAccount.inputFields.tenureDays.errorMessage.minimum": "Minimum is 0",
    "assetLiabilityForms:forms.bankAccount.inputFields.tenureDays.errorMessage.maximum": "Maximum is 31",
    "assetLiabilityForms:forms.listedAssets.title": "Fill in the listed asset details",
    "assetLiabilityForms:forms.listedAssets.inputFields.securityName.label": "Security name",
    "assetLiabilityForms:forms.listedAssets.inputFields.securityName.placeholder": "Search by name, tickr or ISIN number",
    "assetLiabilityForms:forms.listedAssets.inputFields.securityName.errorMessage": "Please enter security name, tiker or ISIN number",
    "assetLiabilityForms:forms.listedAssets.inputFields.securityDetails.label": "Security details",
    "assetLiabilityForms:forms.listedAssets.inputFields.brokerName.label": "Custodian (optional)",
    "assetLiabilityForms:forms.listedAssets.inputFields.brokerName.placeholder": "Custodian name is filled in here",
    "assetLiabilityForms:forms.listedAssets.inputFields.brokerName.errorMessage": "Please enter custodian name",
    "assetLiabilityForms:forms.listedAssets.inputFields.assetType.label": "Asset type",
    "assetLiabilityForms:forms.listedAssets.inputFields.assetType.placeholder": "Select type",
    "assetLiabilityForms:forms.listedAssets.inputFields.assetType.errorMessage": "Please select asset type",
    "assetLiabilityForms:forms.listedAssets.inputFields.assetType.options.equity": "Equity",
    "assetLiabilityForms:forms.listedAssets.inputFields.assetType.options.fixedIncome": "Fixed Income",
    "assetLiabilityForms:forms.listedAssets.inputFields.assetType.options.etfs": "ETFs",
    "assetLiabilityForms:forms.listedAssets.inputFields.assetType.options.mutualFunds": "Mutual Funds",
    "assetLiabilityForms:forms.listedAssets.inputFields.country.label": "Country",
    "assetLiabilityForms:forms.listedAssets.inputFields.country.placeholder": "Type or select a country",
    "assetLiabilityForms:forms.listedAssets.inputFields.country.errorMessage": "Please select country",
    "assetLiabilityForms:forms.listedAssets.inputFields.acquisitionDate.label": "Acquisition date",
    "assetLiabilityForms:forms.listedAssets.inputFields.acquisitionDate.placeholder": "DD\/MM\/YYYY",
    "assetLiabilityForms:forms.listedAssets.inputFields.acquisitionDate.errorMessage": "Please selct acquisition date",
    "assetLiabilityForms:forms.listedAssets.inputFields.acquisitionDate.tooltip": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    "assetLiabilityForms:forms.listedAssets.inputFields.currency.label": "Currency",
    "assetLiabilityForms:forms.listedAssets.inputFields.currency.placeholder": "Type or select an currency",
    "assetLiabilityForms:forms.listedAssets.inputFields.currency.errorMessage": "Please select currency",
    "assetLiabilityForms:forms.listedAssets.inputFields.value.label": "Unit cost",
    "assetLiabilityForms:forms.listedAssets.inputFields.value.placeholder": "Enter unit",
    "assetLiabilityForms:forms.listedAssets.inputFields.value.errorMessage": "Please enter value",
    "assetLiabilityForms:forms.listedAssets.inputFields.quantity.label": "Number of units",
    "assetLiabilityForms:forms.listedAssets.inputFields.quantity.placeholder": "Enter number",
    "assetLiabilityForms:forms.listedAssets.inputFields.quantity.errorMessage": "Please enter quantity",
    "assetLiabilityForms:forms.listedAssets.inputFields.totalCost.label": "Total cost",
    "assetLiabilityForms:forms.privateEquity.title": "Fill in private equity details",
    "assetLiabilityForms:forms.privateEquity.inputFields.name.label": "Name",
    "assetLiabilityForms:forms.privateEquity.inputFields.name.placeholder": "Type the name of your private equity",
    "assetLiabilityForms:forms.privateEquity.inputFields.name.errorMessage": "Please enter name",
    "assetLiabilityForms:forms.privateEquity.inputFields.custodian.label": "Custodian (optional)",
    "assetLiabilityForms:forms.privateEquity.inputFields.custodian.placeholder": "Type the name of custodian",
    "assetLiabilityForms:forms.privateEquity.inputFields.country.label": "Country",
    "assetLiabilityForms:forms.privateEquity.inputFields.country.placeholder": "Type or select a country",
    "assetLiabilityForms:forms.privateEquity.inputFields.country.errorMessage": "Please select country",
    "assetLiabilityForms:forms.privateEquity.inputFields.currency.label": "Currency",
    "assetLiabilityForms:forms.privateEquity.inputFields.currency.placeholder": "Type or select an currency",
    "assetLiabilityForms:forms.privateEquity.inputFields.currency.errorMessage": "Please select currency",
    "assetLiabilityForms:forms.privateEquity.inputFields.initialInvestmentAmount.label": "Initial investment amount",
    "assetLiabilityForms:forms.privateEquity.inputFields.initialInvestmentAmount.placeholder": "Book value of initial investment",
    "assetLiabilityForms:forms.privateEquity.inputFields.initialInvestmentAmount.errorMessage": "Please enter initial investment amount",
    "assetLiabilityForms:forms.privateEquity.inputFields.currentValue.label": "Current value",
    "assetLiabilityForms:forms.privateEquity.inputFields.currentValue.placeholder": "The current day value of the asset",
    "assetLiabilityForms:forms.privateEquity.inputFields.currentValue.errorMessage": "Please enter current value",
    "assetLiabilityForms:forms.privateEquity.inputFields.acquisitionDate.label": "Acquisition date",
    "assetLiabilityForms:forms.privateEquity.inputFields.acquisitionDate.placeholder": "DD\/MM\/YYYY",
    "assetLiabilityForms:forms.privateEquity.inputFields.acquisitionDate.errorMessage": "Please select acquisition date",
    "assetLiabilityForms:forms.privateEquity.inputFields.acquisitionDate.tooltip": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    "assetLiabilityForms:forms.privateEquity.inputFields.valuationDate.label": "Valuation date",
    "assetLiabilityForms:forms.privateEquity.inputFields.valuationDate.placeholder": "DD\/MM\/YYYY",
    "assetLiabilityForms:forms.privateEquity.inputFields.valuationDate.errorMessage": "Please select valuation date",
    "assetLiabilityForms:forms.privateEquity.inputFields.valuationDate.tooltip": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    "assetLiabilityForms:forms.privateDebt.title": "Fill in private debt details",
    "assetLiabilityForms:forms.privateDebt.inputFields.name.label": "Name",
    "assetLiabilityForms:forms.privateDebt.inputFields.name.placeholder": "Type the name of your private debt",
    "assetLiabilityForms:forms.privateDebt.inputFields.name.errorMessage": "Please enter name",
    "assetLiabilityForms:forms.privateDebt.inputFields.custodian.label": "Custodian (optional)",
    "assetLiabilityForms:forms.privateDebt.inputFields.custodian.placeholder": "Type the name of custodian",
    "assetLiabilityForms:forms.privateDebt.inputFields.country.label": "Country",
    "assetLiabilityForms:forms.privateDebt.inputFields.country.placeholder": "Type or select a country",
    "assetLiabilityForms:forms.privateDebt.inputFields.country.errorMessage": "Please select country",
    "assetLiabilityForms:forms.privateDebt.inputFields.currency.label": "Currency",
    "assetLiabilityForms:forms.privateDebt.inputFields.currency.placeholder": "Type or select an currency",
    "assetLiabilityForms:forms.privateDebt.inputFields.currency.errorMessage": "Please select currency",
    "assetLiabilityForms:forms.privateDebt.inputFields.initialInvestmentAmount.label": "Initial investment amount",
    "assetLiabilityForms:forms.privateDebt.inputFields.initialInvestmentAmount.placeholder": "Book value of initial investment",
    "assetLiabilityForms:forms.privateDebt.inputFields.initialInvestmentAmount.errorMessage": "Please enter initial investment amount",
    "assetLiabilityForms:forms.privateDebt.inputFields.currentValue.label": "Current value",
    "assetLiabilityForms:forms.privateDebt.inputFields.currentValue.placeholder": "The current day value of the asset",
    "assetLiabilityForms:forms.privateDebt.inputFields.currentValue.errorMessage": "Please enter current value",
    "assetLiabilityForms:forms.privateDebt.inputFields.acquisitionDate.label": "Acquisition date",
    "assetLiabilityForms:forms.privateDebt.inputFields.acquisitionDate.placeholder": "DD\/MM\/YYYY",
    "assetLiabilityForms:forms.privateDebt.inputFields.acquisitionDate.errorMessage": "Please select acquisition date",
    "assetLiabilityForms:forms.privateDebt.inputFields.acquisitionDate.tooltip": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    "assetLiabilityForms:forms.privateDebt.inputFields.valuationDate.label": "Valuation date",
    "assetLiabilityForms:forms.privateDebt.inputFields.valuationDate.placeholder": "DD\/MM\/YYYY",
    "assetLiabilityForms:forms.privateDebt.inputFields.valuationDate.errorMessage": "Please select valuation date",
    "assetLiabilityForms:forms.privateDebt.inputFields.valuationDate.tooltip": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    "assetLiabilityForms:labels.endTerm": "End term",
    "assetLiabilityForms:labels.linkAccount": "Link your bank account",
    "assetLiabilityForms:labels.footerDisclaimer": "You can add another asset on the next screen",
    "common:errors.somethingWentWrong": "Something went wrong",
    "common:errors.numberAllowed": "Only numbers are allowed",
    "common:button.addAsset": "Add Asset",
    "common:button.back": "Back",
    "common:button.submit": "Submit",
    "common:help.heading": "Need support?",
    "common:help.link.support": "Get in touch",
    "common:help.button.whatsApp": "WhatsApp",
    "common:help.button.email": "Email us",
    "common:help.subheading": "Get in touch",
    "common:help.contact": "Contact",
    "common:nav.heading": "Menu",
    "common:nav.links.home": "Home",
    "common:nav.links.signout": "Sign out",
    "common:formExitModal.buttons.backForm": "Back to form",
    "common:formExitModal.buttons.exitForm": "Exit Form",
    "common:labels.asset": "Asset",
    "common:labels.liability": "Liability",
    "common:select.noOptions": "No options",
    "countries:BD": "Bangladesh",
    "countries:BE": "Belgium",
    "countries:BF": "Burkina Faso",
    "countries:BG": "Bulgaria",
    "countries:BA": "Bosnia and Herzegovina",
    "countries:BB": "Barbados",
    "countries:WF": "Wallis and Futuna",
    "countries:BL": "Saint Barthelemy",
    "countries:BM": "Bermuda",
    "countries:BN": "Brunei",
    "countries:BO": "Bolivia",
    "countries:BH": "Bahrain",
    "countries:BI": "Burundi",
    "countries:BJ": "Benin",
    "countries:BT": "Bhutan",
    "countries:JM": "Jamaica",
    "countries:BV": "Bouvet Island",
    "countries:BW": "Botswana",
    "countries:WS": "Samoa",
    "countries:BQ": "Islands of Bonaire, Sint Eustatius and Saba",
    "countries:BR": "Brazil",
    "countries:BS": "Bahamas",
    "countries:JE": "Jersey",
    "countries:BY": "Belarus",
    "countries:BZ": "Belize",
    "countries:RU": "Russia",
    "countries:RW": "Rwanda",
    "countries:RS": "Serbia",
    "countries:TL": "East Timor",
    "countries:RE": "Reunion",
    "countries:TM": "Turkmenistan",
    "countries:TJ": "Tajikistan",
    "countries:RO": "Romania",
    "countries:TK": "Tokelau",
    "countries:GW": "Guinea-Bissau",
    "countries:GU": "Guam",
    "countries:GT": "Guatemala",
    "countries:GS": "South Georgia and the South Sandwich Islands",
    "countries:GR": "Greece",
    "countries:GQ": "Equatorial Guinea",
    "countries:GP": "Guadeloupe",
    "countries:JP": "Japan",
    "countries:GY": "Guyana",
    "countries:GG": "Guernsey",
    "countries:GF": "French Guiana",
    "countries:GE": "Georgia",
    "countries:GD": "Grenada",
    "countries:GB": "United Kingdom",
    "countries:GA": "Gabon",
    "countries:SV": "El Salvador",
    "countries:GN": "Guinea",
    "countries:GM": "Gambia",
    "countries:GL": "Greenland",
    "countries:GI": "Gibraltar",
    "countries:GH": "Ghana",
    "countries:OM": "Oman",
    "countries:TN": "Tunisia",
    "countries:JO": "Jordan",
    "countries:HR": "Croatia",
    "countries:HT": "Haiti",
    "countries:HU": "Hungary",
    "countries:HK": "Hong Kong",
    "countries:HN": "Honduras",
    "countries:HM": "Heard Island and McDonald Islands",
    "countries:VE": "Venezuela",
    "countries:PR": "Puerto Rico",
    "countries:PS": "Palestinian Territory",
    "countries:PW": "Palau",
    "countries:PT": "Portugal",
    "countries:SJ": "Svalbard and Jan Mayen",
    "countries:PY": "Paraguay",
    "countries:IQ": "Iraq",
    "countries:PA": "Panama",
    "countries:PF": "French Polynesia",
    "countries:PG": "Papua New Guinea",
    "countries:PE": "Peru",
    "countries:PK": "Pakistan",
    "countries:PH": "Philippines",
    "countries:PN": "Pitcairn",
    "countries:PL": "Poland",
    "countries:PM": "Saint Pierre and Miquelon",
    "countries:ZM": "Zambia",
    "countries:EH": "Western Sahara",
    "countries:EE": "Estonia",
    "countries:EG": "Egypt",
    "countries:ZA": "South Africa",
    "countries:EC": "Ecuador",
    "countries:IT": "Italy",
    "countries:VN": "Vietnam",
    "countries:SB": "Solomon Islands",
    "countries:ET": "Ethiopia",
    "countries:SO": "Somalia",
    "countries:ZW": "Zimbabwe",
    "countries:SA": "Saudi Arabia",
    "countries:ES": "Spain",
    "countries:ER": "Eritrea",
    "countries:ME": "Montenegro",
    "countries:MD": "Moldova",
    "countries:MG": "Madagascar",
    "countries:MF": "Saint Martin",
    "countries:MA": "Morocco",
    "countries:MC": "Monaco",
    "countries:UZ": "Uzbekistan",
    "countries:MM": "Myanmar",
    "countries:ML": "Mali",
    "countries:MO": "Macao",
    "countries:MN": "Mongolia",
    "countries:MH": "Marshall Islands",
    "countries:MK": "Macedonia",
    "countries:MU": "Mauritius",
    "countries:MT": "Malta",
    "countries:MW": "Malawi",
    "countries:MV": "Maldives",
    "countries:MQ": "Martinique",
    "countries:MP": "Northern Mariana Islands",
    "countries:MS": "Montserrat",
    "countries:MR": "Mauritania",
    "countries:IM": "Isle of Man",
    "countries:UG": "Uganda",
    "countries:TZ": "Tanzania",
    "countries:MY": "Malaysia",
    "countries:MX": "Mexico",
    "countries:IL": "Israel",
    "countries:FR": "France",
    "countries:IO": "British Indian Ocean Territory",
    "countries:SH": "Saint Helena",
    "countries:FI": "Finland",
    "countries:FJ": "Fiji",
    "countries:FK": "Falkland Islands",
    "countries:FM": "Micronesia",
    "countries:FO": "Faroe Islands",
    "countries:NI": "Nicaragua",
    "countries:NL": "Netherlands",
    "countries:NO": "Norway",
    "countries:NA": "Namibia",
    "countries:VU": "Vanuatu",
    "countries:NC": "New Caledonia",
    "countries:NE": "Niger",
    "countries:NF": "Norfolk Island",
    "countries:NG": "Nigeria",
    "countries:NZ": "New Zealand",
    "countries:NP": "Nepal",
    "countries:NR": "Nauru",
    "countries:NU": "Niue",
    "countries:CK": "Cook Islands",
    "countries:XK": "Kosovo",
    "countries:CI": "Ivory Coast",
    "countries:CH": "Switzerland",
    "countries:CO": "Colombia",
    "countries:CN": "China",
    "countries:CM": "Cameroon",
    "countries:CL": "Chile",
    "countries:CC": "Cocos Islands",
    "countries:CA": "Canada",
    "countries:CG": "Republic of the Congo",
    "countries:CF": "Central African Republic",
    "countries:CD": "Democratic Republic of the Congo",
    "countries:CZ": "Czech Republic",
    "countries:CY": "Cyprus",
    "countries:CX": "Christmas Island",
    "countries:CR": "Costa Rica",
    "countries:CW": "Curacao",
    "countries:CV": "Cape Verde",
    "countries:CU": "Cuba",
    "countries:SZ": "Swaziland",
    "countries:SY": "Syria",
    "countries:SX": "Sint Maarten",
    "countries:KG": "Kyrgyzstan",
    "countries:KE": "Kenya",
    "countries:SS": "South Sudan",
    "countries:SR": "Suriname",
    "countries:KI": "Kiribati",
    "countries:KH": "Cambodia",
    "countries:KN": "Saint Kitts and Nevis",
    "countries:KM": "Comoros",
    "countries:ST": "Sao Tome and Principe",
    "countries:SK": "Slovakia",
    "countries:KR": "South Korea",
    "countries:SI": "Slovenia",
    "countries:KP": "North Korea",
    "countries:KW": "Kuwait",
    "countries:SN": "Senegal",
    "countries:SM": "San Marino",
    "countries:SL": "Sierra Leone",
    "countries:SC": "Seychelles",
    "countries:KZ": "Kazakhstan",
    "countries:KY": "Cayman Islands",
    "countries:SG": "Singapore",
    "countries:SE": "Sweden",
    "countries:SD": "Sudan",
    "countries:DO": "Dominican Republic",
    "countries:DM": "Dominica",
    "countries:DJ": "Djibouti",
    "countries:DK": "Denmark",
    "countries:VG": "British Virgin Islands",
    "countries:DE": "Germany",
    "countries:YE": "Yemen",
    "countries:DZ": "Algeria",
    "countries:US": "United States",
    "countries:UY": "Uruguay",
    "countries:YT": "Mayotte",
    "countries:UM": "United States Minor Outlying Islands",
    "countries:LB": "Lebanon",
    "countries:LC": "Saint Lucia",
    "countries:LA": "Laos",
    "countries:TV": "Tuvalu",
    "countries:TW": "Taiwan",
    "countries:TT": "Trinidad and Tobago",
    "countries:TR": "Turkey",
    "countries:LK": "Sri Lanka",
    "countries:LI": "Liechtenstein",
    "countries:LV": "Latvia",
    "countries:TO": "Tonga",
    "countries:LT": "Lithuania",
    "countries:LU": "Luxembourg",
    "countries:LR": "Liberia",
    "countries:LS": "Lesotho",
    "countries:TH": "Thailand",
    "countries:TF": "French Southern Territories",
    "countries:TG": "Togo",
    "countries:TD": "Chad",
    "countries:TC": "Turks and Caicos Islands",
    "countries:LY": "Libya",
    "countries:VA": "Vatican",
    "countries:VC": "Saint Vincent and the Grenadines",
    "countries:AE": "United Arab Emirates",
    "countries:AD": "Andorra",
    "countries:AG": "Antigua and Barbuda",
    "countries:AF": "Afghanistan",
    "countries:AI": "Anguilla",
    "countries:VI": "U.S. Virgin Islands",
    "countries:IS": "Iceland",
    "countries:IR": "Iran",
    "countries:AM": "Armenia",
    "countries:AL": "Albania",
    "countries:AO": "Angola",
    "countries:AQ": "Antarctica",
    "countries:AS": "American Samoa",
    "countries:AR": "Argentina",
    "countries:AU": "Australia",
    "countries:AT": "Austria",
    "countries:AW": "Aruba",
    "countries:IN": "India",
    "countries:AX": "Aland Islands",
    "countries:AZ": "Azerbaijan",
    "countries:IE": "Ireland",
    "countries:ID": "Indonesia",
    "countries:UA": "Ukraine",
    "countries:QA": "Qatar",
    "countries:MZ": "Mozambique",
    "home:heading": "Wealth Overview",
    "home:subheading": "Summary",
    "home:label.totalNetWorth": "Total Net Worth",
    "home:label.assets": "Assets",
    "home:label.liabilities": "Liabilities",
    "home:label.yourAssets": "Your Assets",
    "home:text.lastDays": "Change in last {{days}} days",
    "home:select.duration.options.seven": "Last 7 days",
    "home:select.duration.options.thirty": "Last 30 days",
    "home:widget.geography.title": "Geographical Exposure",
    "home:widget.geography.label.continents": "Continent",
    "home:widget.geography.label.allocation": "Allocation",
    "home:widget.geography.button.more": "More",
    "manage:page.title": "Join our Platform",
    "manage:page.description": "Create my account",
    "manage:heading": "Hi {{name}}!",
    "manage:subHeading": "Add your assets and liabilities to combine them in one single platform",
    "manage:assetAndLiability.title": "Add an Asset \/ Liability",
    "manage:assetAndLiability.description": "You can always add more later.",
    "manage:assetAndLiability.assetAndLiabilityList.bankAccount.title": "Bank account",
    "manage:assetAndLiability.assetAndLiabilityList.bankAccount.description": "Current account, savings account or term deposit account.",
    "manage:assetAndLiability.assetAndLiabilityList.realEstate.title": "Real estate",
    "manage:assetAndLiability.assetAndLiabilityList.realEstate.description": "Investment in a residential, commercial or land real estate.",
    "manage:assetAndLiability.assetAndLiabilityList.listedAssets.title": "Listed assets",
    "manage:assetAndLiability.assetAndLiabilityList.listedAssets.description": "Investment in stocks, bonds, ETFs or mutual funds.",
    "manage:assetAndLiability.assetAndLiabilityList.privateEquity.title": "Private equity",
    "manage:assetAndLiability.assetAndLiabilityList.privateEquity.description": "Investment in a company that is not publicly listed or traded.",
    "manage:assetAndLiability.assetAndLiabilityList.privateDebt.title": "Private debt",
    "manage:assetAndLiability.assetAndLiabilityList.privateDebt.description": "Investment to acquire the debt of a private company.",
    "manage:assetAndLiability.assetAndLiabilityList.others.title": "Others",
    "manage:assetAndLiability.assetAndLiabilityList.others.description": "Other investments including vehicles, jewelry or pieces of art.",
    "manage:assetAndLiability.assetAndLiabilityList.loan.title": "Loan",
    "manage:assetAndLiability.assetAndLiabilityList.loan.description": "Home, car, business or personal loan.",
    "manage:labels.footerDisclaimer": "You can add another asset on the next page",
    "manage:securityInfoWidget.title": "Your privacy & data security are our priority",
    "manage:securityInfoWidget.description": "Your data is private and protected in transit with TLS 1.2 technology.",
    "profile:page.title": "Profile",
    "profile:page.description": "Manage your personal details.",
    "profile:changePassword.heading": "Change Password",
    "profile:changePassword.text.password": "Password",
    "profile:changePassword.button.change": "Change Password",
    "profile:tabs.heading": "Settings",
    "profile:tabs.personal.name": "Personal Details",
    "profile:tabs.personal.headings.personalInfo": "Personal Information",
    "profile:tabs.personal.headings.contactInfo": "Contact Information",
    "profile:tabs.personal.fields.label.firstName": "First Name",
    "profile:tabs.personal.fields.label.lastName": "Last Name",
    "profile:tabs.personal.fields.label.email": "Personal Email",
    "profile:tabs.personal.fields.label.primaryPhoneNumber": "Primary phone number",
    "profile:tabs.personal.placeholders.firstName": "Enter First Name",
    "profile:tabs.personal.placeholders.lastName": "Enter Last Name",
    "profile:tabs.preferences.name": "Preferences",
    "profile:tabs.preferences.heading": "Preferred language",
    "profile:tabs.preferences.subHeading": "Select the preferred language that will be used every time you login in the platform.",
    "profile:tabs.preferences.button.applyChanges": "Apply changes",
    "profile:tabs.linkedAccounts.name": "Linked Accounts",
    "assets:label.percentageText": "% of \$",
    "home:widget.summaryCard.tooltip.assets": "Includes {{count}} new assets worth USD {{change}}.",
    "home:widget.summaryCard.tooltip.liabilities": "Includes {{count}} new liabilities worth USD {{change}}.",
    "assetLiabilityForms:page.edit.title": "Edit {{assetName}}",
    "assetLiabilityForms:page.edit.description": "Edit {{assetName}}",
    "assetLiabilityForms:heading.others": "Add other asset",
    "assetLiabilityForms:heading.realEstate": "Add Real Estate",
    "assetLiabilityForms:heading.loan": "Add loan details",
    "assetLiabilityForms:heading.edit.others": "Edit other asset details",
    "assetLiabilityForms:heading.edit.bankAccount": "Edit bank account",
    "assetLiabilityForms:heading.edit.realEstate": "Edit real estate details",
    "assetLiabilityForms:heading.edit.privateEquity": "Edit private equity details",
    "assetLiabilityForms:heading.edit.privateDebt": "Edit real estate details",
    "assetLiabilityForms:heading.edit.listedAssets": "Edit listed asset details",
    "assetLiabilityForms:heading.edit.loan": "Edit liability detail",
    "assetLiabilityForms:assets.others": "Others",
    "assetLiabilityForms:assets.realEstate": "Real Estate",
    "assetLiabilityForms:assets.loan": "Loan",
    "assetLiabilityForms:subHeading.others": "Uncategorized other investments including vehicles, jewelry and art.",
    "assetLiabilityForms:subHeading.realEstate": "Investments made in residential, commercial and land real estate.",
    "assetLiabilityForms:subHeading.loan": "Mortgage, personal loan, vehicle loan etc.",
    "assetLiabilityForms:forms.bankAccount.inputFields.accountType.tooltip": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    "assetLiabilityForms:forms.listedAssets.inputFields.value.tooltip": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    "assetLiabilityForms:forms.listedAssets.inputFields.couponRate.label": "Coupon Rate",
    "assetLiabilityForms:forms.listedAssets.inputFields.couponRate.placeholder": "00",
    "assetLiabilityForms:forms.listedAssets.inputFields.couponRate.errorMessage.message": "Please enter coupon rate",
    "assetLiabilityForms:forms.listedAssets.inputFields.couponRate.errorMessage.minimum": "Minimum is 0.1%",
    "assetLiabilityForms:forms.listedAssets.inputFields.couponRate.errorMessage.maximum": "Maximum is 100%",
    "assetLiabilityForms:forms.listedAssets.inputFields.couponRate.errorMessage.max3digits": "The units should be a decimal with maximum three digits",
    "assetLiabilityForms:forms.listedAssets.inputFields.maturityDate.label": "Maturity date",
    "assetLiabilityForms:forms.listedAssets.inputFields.maturityDate.placeholder": "DD\/MM\/YYYY",
    "assetLiabilityForms:forms.listedAssets.inputFields.maturityDate.errorMessage": "Please select maturity date",
    "assetLiabilityForms:forms.others.title": "Fill in your asset details",
    "assetLiabilityForms:forms.others.inputFields.name.label": "Name",
    "assetLiabilityForms:forms.others.inputFields.name.placeholder": "Name of your asset",
    "assetLiabilityForms:forms.others.inputFields.name.errorMessage": "Please enter asset name",
    "assetLiabilityForms:forms.others.inputFields.wealthManager.label": "Wealth manager (optional)",
    "assetLiabilityForms:forms.others.inputFields.wealthManager.placeholder": "Type the name of broker",
    "assetLiabilityForms:forms.others.inputFields.wealthManager.errorMessage": "Please enter wealth manager name",
    "assetLiabilityForms:forms.others.inputFields.assetType.label": "Type of asset",
    "assetLiabilityForms:forms.others.inputFields.assetType.placeholder": "Type or select the asset type",
    "assetLiabilityForms:forms.others.inputFields.assetType.errorMessage": "Please type or select asset type",
    "assetLiabilityForms:forms.others.inputFields.assetType.options.autoMobile": "Automobile",
    "assetLiabilityForms:forms.others.inputFields.assetType.options.yacht": "Yacht",
    "assetLiabilityForms:forms.others.inputFields.assetType.options.privateJet": "Private Jet",
    "assetLiabilityForms:forms.others.inputFields.assetType.options.watch": "Watch",
    "assetLiabilityForms:forms.others.inputFields.assetType.options.painting": "Painting",
    "assetLiabilityForms:forms.others.inputFields.assetType.options.jewelry": "Jewelry",
    "assetLiabilityForms:forms.others.inputFields.assetType.options.other": "Other",
    "assetLiabilityForms:forms.others.inputFields.valuationDate.label": "Valuation date",
    "assetLiabilityForms:forms.others.inputFields.valuationDate.placeholder": "DD\/MM\/YYYY",
    "assetLiabilityForms:forms.others.inputFields.valuationDate.errorMessage": "Please selct valuation date",
    "assetLiabilityForms:forms.others.inputFields.valuationDate.tooltip": "This field is being captured to calculate the performance parameters like returns etc.",
    "assetLiabilityForms:forms.others.inputFields.country.label": "Country",
    "assetLiabilityForms:forms.others.inputFields.country.placeholder": "Type or select a country",
    "assetLiabilityForms:forms.others.inputFields.country.errorMessage": "Please type or select country",
    "assetLiabilityForms:forms.others.inputFields.currency.label": "Currency",
    "assetLiabilityForms:forms.others.inputFields.currency.placeholder": "Type or select an currency",
    "assetLiabilityForms:forms.others.inputFields.currency.errorMessage": "Please select currency",
    "assetLiabilityForms:forms.others.inputFields.units.label": "Number of units",
    "assetLiabilityForms:forms.others.inputFields.units.placeholder": "00",
    "assetLiabilityForms:forms.others.inputFields.units.errorMessage": "Please enter units",
    "assetLiabilityForms:forms.others.inputFields.acquisitionCost.label": "Acquisition cost",
    "assetLiabilityForms:forms.others.inputFields.acquisitionCost.placeholder": "Type the purchase price of asset",
    "assetLiabilityForms:forms.others.inputFields.acquisitionCost.errorMessage": "Please enter the acquisition cost",
    "assetLiabilityForms:forms.others.inputFields.acquisitionCost.tooltip": " This field is to be entered as cost price per unit and is being captured to calculate the performance parameters like returns etc.",
    "assetLiabilityForms:forms.others.inputFields.acquisitionDate.label": "Acquisition date",
    "assetLiabilityForms:forms.others.inputFields.acquisitionDate.placeholder": "DD\/MM\/YYYY",
    "assetLiabilityForms:forms.others.inputFields.acquisitionDate.errorMessage": "Please selct acquisition date",
    "assetLiabilityForms:forms.others.inputFields.acquisitionDate.tooltip": "This field is being captured to calculate the performance parameters like returns etc.",
    "assetLiabilityForms:forms.others.inputFields.acquisitionDate.comparisonError": "Acquisition date should be less than valuation date",
    "assetLiabilityForms:forms.others.inputFields.ownerShip.label": "Ownership",
    "assetLiabilityForms:forms.others.inputFields.ownerShip.placeholder": "Type in a figure e.g 72%",
    "assetLiabilityForms:forms.others.inputFields.ownerShip.errorMessage": "Ownership should not exceed 100%",
    "assetLiabilityForms:forms.others.inputFields.securityDetails.label": "Security details",
    "assetLiabilityForms:forms.others.inputFields.valuePerUnit.label": "Value per unit (optional)",
    "assetLiabilityForms:forms.others.inputFields.valuePerUnit.placeholder": "The current day value of the asset",
    "assetLiabilityForms:forms.others.inputFields.valuePerUnit.errorMessage": "Please enter value per unit",
    "assetLiabilityForms:forms.others.inputFields.currentDayValue.label": "Current day value",
    "assetLiabilityForms:forms.realEstate.title": "Fill in your property details",
    "assetLiabilityForms:forms.realEstate.inputFields.name.label": "Name",
    "assetLiabilityForms:forms.realEstate.inputFields.name.placeholder": "A nickname to identify your property",
    "assetLiabilityForms:forms.realEstate.inputFields.name.errorMessage": "Please enter name",
    "assetLiabilityForms:forms.realEstate.inputFields.typeOfRealEstate.label": "Type of real estate",
    "assetLiabilityForms:forms.realEstate.inputFields.typeOfRealEstate.placeholder": "Select type of real estate",
    "assetLiabilityForms:forms.realEstate.inputFields.typeOfRealEstate.errorMessage": "Please select type of real estate",
    "assetLiabilityForms:forms.realEstate.inputFields.typeOfRealEstate.options.residential": "Residential",
    "assetLiabilityForms:forms.realEstate.inputFields.typeOfRealEstate.options.commercial": "Commercial",
    "assetLiabilityForms:forms.realEstate.inputFields.typeOfRealEstate.options.land": "Land",
    "assetLiabilityForms:forms.realEstate.inputFields.address.label": "Address (optional)",
    "assetLiabilityForms:forms.realEstate.inputFields.address.placeholder": "Address",
    "assetLiabilityForms:forms.realEstate.inputFields.address.errorMessage": "Please enter address",
    "assetLiabilityForms:forms.realEstate.inputFields.country.label": "Country",
    "assetLiabilityForms:forms.realEstate.inputFields.country.placeholder": "Type or select a country",
    "assetLiabilityForms:forms.realEstate.inputFields.country.errorMessage": "Please select country",
    "assetLiabilityForms:forms.realEstate.inputFields.currency.label": "Currency",
    "assetLiabilityForms:forms.realEstate.inputFields.currency.placeholder": "Type or select an currency",
    "assetLiabilityForms:forms.realEstate.inputFields.currency.errorMessage": "Please select currency",
    "assetLiabilityForms:forms.realEstate.inputFields.numberofUnits.label": "Number of units",
    "assetLiabilityForms:forms.realEstate.inputFields.numberofUnits.placeholder": "No. of Units",
    "assetLiabilityForms:forms.realEstate.inputFields.numberofUnits.errorMessage.minimum": "Minimum value is 1",
    "assetLiabilityForms:forms.realEstate.inputFields.numberofUnits.errorMessage.error": "Please enter number of units",
    "assetLiabilityForms:forms.realEstate.inputFields.numberofUnits.errorMessage.maxError": "Maximum value is 100",
    "assetLiabilityForms:forms.realEstate.inputFields.acquisitionCostPerUnit.label": "Acquisition cost per unit",
    "assetLiabilityForms:forms.realEstate.inputFields.acquisitionCostPerUnit.placeholder": "Type a cost",
    "assetLiabilityForms:forms.realEstate.inputFields.acquisitionCostPerUnit.errorMessage": "Please enter acquisition cost per unit",
    "assetLiabilityForms:forms.realEstate.inputFields.acquisitionCostPerUnit.tooltip": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    "assetLiabilityForms:forms.realEstate.inputFields.yourOwnership.label": "Your ownership",
    "assetLiabilityForms:forms.realEstate.inputFields.yourOwnership.placeholder": "Type in a figure e.g 72%",
    "assetLiabilityForms:forms.realEstate.inputFields.yourOwnership.errorMessage.minimum": "Minimum is 0.1%",
    "assetLiabilityForms:forms.realEstate.inputFields.yourOwnership.errorMessage.maximum": "Maximum is 100%",
    "assetLiabilityForms:forms.realEstate.inputFields.valuePerUnit.label": "Value per unit (optional)",
    "assetLiabilityForms:forms.realEstate.inputFields.valuePerUnit.placeholder": "Current market value",
    "assetLiabilityForms:forms.realEstate.inputFields.valuePerUnit.tooltip": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    "assetLiabilityForms:forms.realEstate.inputFields.valuePerUnit.errorMessage.minimum": "Minimum is 0",
    "assetLiabilityForms:forms.realEstate.inputFields.acquisitionDate.label": "Acquisition date",
    "assetLiabilityForms:forms.realEstate.inputFields.acquisitionDate.placeholder": "DD\/MM\/YYYY",
    "assetLiabilityForms:forms.realEstate.inputFields.acquisitionDate.errorMessage": "Please select acquisition date",
    "assetLiabilityForms:forms.realEstate.inputFields.acquisitionDate.tooltip": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    "assetLiabilityForms:forms.realEstate.inputFields.valuationDate.label": "Valuation date (optional)",
    "assetLiabilityForms:forms.realEstate.inputFields.valuationDate.placeholder": "DD\/MM\/YYYY",
    "assetLiabilityForms:forms.realEstate.inputFields.valuationDate.errorMessage": "Please select valuation date",
    "assetLiabilityForms:forms.realEstate.inputFields.valuationDate.tooltip": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    "assetLiabilityForms:forms.loan.title": "Fill in liability details",
    "assetLiabilityForms:forms.loan.inputFields.name.label": "Name",
    "assetLiabilityForms:forms.loan.inputFields.name.placeholder": "A nickname to identify your loan",
    "assetLiabilityForms:forms.loan.inputFields.name.errorMessage": "Please enter name",
    "assetLiabilityForms:forms.loan.inputFields.bankName.label": "Bank name (optional)",
    "assetLiabilityForms:forms.loan.inputFields.bankName.placeholder": "Your bank name",
    "assetLiabilityForms:forms.loan.inputFields.type.label": "Type",
    "assetLiabilityForms:forms.loan.inputFields.type.placeholder": "Type or select an loan type",
    "assetLiabilityForms:forms.loan.inputFields.type.errorMessage": "Please select loan type",
    "assetLiabilityForms:forms.loan.inputFields.type.options.homeLoan": "Home Loan",
    "assetLiabilityForms:forms.loan.inputFields.type.options.vehicleLoan": "Vehicle Loan",
    "assetLiabilityForms:forms.loan.inputFields.type.options.personalLoan": "Personal Loan",
    "assetLiabilityForms:forms.loan.inputFields.type.options.other": "Other",
    "assetLiabilityForms:forms.loan.inputFields.currency.label": "Currency",
    "assetLiabilityForms:forms.loan.inputFields.currency.placeholder": "Type or select an currency",
    "assetLiabilityForms:forms.loan.inputFields.currency.errorMessage": "Please select currency",
    "assetLiabilityForms:forms.loan.inputFields.loanAmount.label": "Loan amount - outstanding",
    "assetLiabilityForms:forms.loan.inputFields.loanAmount.placeholder": "Type loan amount",
    "assetLiabilityForms:forms.loan.inputFields.loanAmount.errorMessage": "Please enter loan amount",
    "assetLiabilityForms:forms.loan.inputFields.loanAmountSanctioned.label": "Loan amount - sanctioned (optional)",
    "assetLiabilityForms:forms.loan.inputFields.loanAmountSanctioned.placeholder": "Type sanctioned loan amount",
    "assetLiabilityForms:forms.loan.inputFields.loanAmountSanctioned.errorMessage": "Sanctioned amount should be greater than outstanding loan amount",
    "assetLiabilityForms:forms.loan.inputFields.loanAmountSanctioned.tooltip": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    "assetLiabilityForms:forms.loan.inputFields.startDate.label": "Start date (optional)",
    "assetLiabilityForms:forms.loan.inputFields.startDate.placeholder": "DD\/MM\/YYYY",
    "assetLiabilityForms:forms.loan.inputFields.startDate.tooltip": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    "assetLiabilityForms:forms.loan.inputFields.endDate.label": "End date (optional)",
    "assetLiabilityForms:forms.loan.inputFields.endDate.placeholder": "DD\/MM\/YYYY",
    "assetLiabilityForms:forms.loan.inputFields.endDate.tooltip": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    "assetLiabilityForms:forms.loan.inputFields.rate.label": "Rate (optional)",
    "assetLiabilityForms:forms.loan.inputFields.rate.placeholder": "Type in a figure",
    "assetLiabilityForms:forms.loan.inputFields.rate.errorMessage.minimum": "Minimum is 0%",
    "assetLiabilityForms:forms.loan.inputFields.rate.errorMessage.maximum": "Maximum is 100%",
    "assetLiabilityForms:forms.loan.inputFields.monthlyPayment.label": "Monthly payment (optional)",
    "assetLiabilityForms:forms.loan.inputFields.monthlyPayment.tooltip": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    "assetLiabilityForms:forms.loan.inputFields.monthlyPayment.placeholder": "Type monthly payment",
    "assetLiabilityForms:forms.loan.inputFields.monthlyPayment.errorMessage.maximum": "Monthly payment can't be greater than outstanding loan amount",
    "assetLiabilityForms:forms.loan.inputFields.collateral.label": "Collateral (optional)",
    "assetLiabilityForms:forms.loan.inputFields.collateral.options.yes": "Yes",
    "assetLiabilityForms:forms.loan.inputFields.collateral.options.no": "No",
    "assetLiabilityForms:forms.loan.inputFields.insurance.label": "Insurance (optional)",
    "assetLiabilityForms:forms.loan.inputFields.insurance.options.yes": "Yes",
    "assetLiabilityForms:forms.loan.inputFields.insurance.options.no": "No",
    "assetLiabilityForms:labels.endTermIn": "Term ends in",
    "assetLiabilityForms:labels.footerAssetDisclaimer": "You can add another asset on the next screen",
    "assetLiabilityForms:labels.footerLiabilityDisclaimer": "You can add another liability on the next screen",
    "assetLiabilityForms:labels.exchaneRateDate": "Exchange rate for {{date}}",
    "assetLiabilityForms:labels.chooseOnMap": "Choose on map",
    "assetLiabilityForms:labels.removeAsset": "Remove the asset altogether?",
    "assetLiabilityForms:securityInfoWidget.title": "Your money & data security is our utmost priority",
    "assetLiabilityForms:securityInfoWidget.description": "Your credentials & information are never accessible to any other service and is always private. Your data is secured in transit using bank grade TLS 1.2 technology.",
    "assets:page.title": "Assets",
    "assets:heading": "Assets",
    "assets:assets.BankAccount": "Bank Account",
    "assets:assets.ListedAsset": "Listed Assets",
    "assets:assets.OtherAssets": "Others",
    "assets:assets.PrivateEquity": "Private Equity",
    "assets:assets.PrivateDebt": "Private Debt",
    "assets:assets.RealEstate": "Real Estate",
    "assets:assets.Loan": "Loan",
    "assets:label.yourHoldings": "Your holdings",
    "assets:label.netChange": "Net Change",
    "assets:label.last365days": "Last 365 days",
    "assets:label.last30days": "Last 30 days",
    "assets:label.totalMaturityAmount": "Total maturity amount",
    "assets:label.maturityDate": "Maturity date",
    "assets:label.other": "Other",
    "assets:label.itd": "ITD",
    "assets:label.ytd": "YTD",
    "assets:label.usd": "USD",
    "assets:label.title": "Asset Detail",
    "assets:label.description": "Asset Description Details",
    "assets:label.heading": "Home Expense Account",
    "assets:label.balance": "Balance",
    "assets:label.last30Days": "Last 30 days",
    "assets:label.portfolioContribution": "Portfolio contribution",
    "assets:label.lastUpdatedOn": "Last updated on",
    "assets:label.ownershipBased": "Ownership based value",
    "assets:label.totalValue": "Total Value",
    "assets:label.ownership": "Ownership",
    "assets:label.performanceChart": "Performance Chart",
    "assets:breadCrumb.wealthOverview": "Wealth Overview",
    "assets:breadCrumb.assets": "Assets",
    "assets:table.header.assetName": "Asset Name",
    "assets:table.header.currentValue": "Current Value",
    "assets:table.header.itd": "ITD",
    "assets:table.header.ytd": "YTD",
    "assets:table.header.geography": "Geography",
    "assets:table.header.asset": "Asset",
    "assets:table.header.valueItdYtd": "Value\/ITD\/YTD",
    "assets:tooltips.itd": "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,",
    "assets:tooltips.ytd": "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,",
    "assets:charts.title": "Allocation by",
    "assets:charts.tabs.assetClass": "Asset class",
    "assets:charts.tabs.geography": "Geography",
    "assets:charts.tabs.currency": "Currency",
    "assets:charts.daysOption.7days": "Last 7 days",
    "assets:charts.daysOption.30days": "Last 30 days",
    "assets:charts.allocationCharts.heading": "Total Net Worth",
    "assets:charts.allocationCharts.areaChartLabel": "Area Chart",
    "assets:charts.allocationCharts.barChartLabel": "Bar Chart",
    "assets:charts.allocationCharts.legendLabel.bankAccount": "Bank account",
    "assets:charts.allocationCharts.legendLabel.realEstate": "Real Estate",
    "assets:charts.allocationCharts.legendLabel.privateEquity": "Private equity",
    "assets:charts.allocationCharts.legendLabel.publicEquity": "Public equity",
    "assets:charts.allocationCharts.legendLabel.privateDebt": "Private debt",
    "assets:charts.allocationCharts.legendLabel.etfs": "ETFs",
    "assets:charts.allocationCharts.legendLabel.other": "Other",
    "common:errors.phoneNumberLength": "Phone number must be of {{digit}} digits",
    "common:button.addLiability": "Add Liability",
    "common:button.save": "Save",
    "common:button.add": "Add",
    "common:button.edit": "Edit",
    "common:button.deleteAsset": "Delete asset",
    "common:button.deleteLiability": "Delete liability",
    "common:button.connect": "Connect",
    "common:button.viewMore": " View more",
    "common:button.viewLess": " View less",
    "common:button.delete": "Delete",
    "common:button.seeMore": "See more",
    "common:button.editDetails": "Edit details",
    "common:button.ok": "Ok",
    "common:button.skip": "Skip",
    "common:button.next": "Next",
    "common:help.needSupport": "Do you need help?",
    "common:nav.links.assets": "Assets",
    "common:nav.links.liabilities": "Liabilities",
    "common:nav.links.profile": "Profile",
    "common:nav.links.expandOrCollapse": "Expand or collapse the navigation bar",
    "common:submitEnquiryModal.title": "Contact our business support team",
    "common:submitEnquiryModal.description": "Contact us if you have any questions. We will get back to you as soon as possible.",
    "common:submitEnquiryModal.placeholder": "Select contact reason",
    "common:submitEnquiryModal.textarea.placeholder": "Type your message here",
    "common:submitEnquiryModal.reasons.learnMore.label": "I want to learn more about available investment products",
    "common:submitEnquiryModal.reasons.learnMore.value": "I want to have a discussion regarding my wealth dashboard",
    "common:submitEnquiryModal.emailSent.title": "Email sent",
    "common:submitEnquiryModal.emailSent.description": "We will get back to you as soon as possible at the email address you have provided.",
    "common:formSuccessModal.description": "You are ready to take charge of your wealth",
    "common:formSuccessModal.startingBalance": "Starting balance",
    "common:formSuccessModal.newUser.title": "You’re off to a great start",
    "common:formSuccessModal.newUser.description": "Your {{assetName}} {{assetType}} has been successfully added to your wealth overview",
    "common:formSuccessModal.newUser.netWorth": "Your net worth is",
    "common:deleteAssetModal.title": "Are you sure you want to delete “{{assetName}}”?",
    "common:deleteAssetModal.description": "This action cannot be reversed",
    "common:labels.years": "Years",
    "common:labels.months": "Months",
    "common:labels.mins": "mins",
    "common:labels.days": "days",
    "common:labels.custodianBank": "Custodian bank",
    "common:labels.select": "Select",
    "common:select.placeholder": "Select",
    "common:assetClass.RealEstate": "Real estate",
    "common:assetClass.PrivateEquity": "Private equity",
    "common:assetClass.PrivateDebt": "Private debt",
    "common:assetClass.ListedAsset": "Listed assets",
    "common:assetClass.BankAccount": "Bank account",
    "common:assetClass.OtherAsset": "Others",
    "common:dashboardErrorStateWidget.title": "Looks like something went wrong.",
    "common:dashboardErrorStateWidget.description": "Please try checking back again in a few moments.",
    "common:guidedOnBoardingModalStepper.selectAsset.title": "Select your assets",
    "common:guidedOnBoardingModalStepper.firstAsset.title": "Add your assets",
    "common:guidedOnBoardingModalStepper.viewDashboard.title": "View your dashboard",
    "home:widget.assetClassAllocation.title": "Asset Class Exposure",
    "home:widget.assetClassAllocation.label.assetClass": "Asset Class",
    "home:widget.assetClassAllocation.label.allocation": "Allocation",
    "home:widget.assetClassAllocation.button.more": "More",
    "home:dashboardCharts.heading": "Total Net Worth",
    "home:dashboardCharts.areaChartLabel": "Area Chart",
    "home:dashboardCharts.barChartLabel": "Bar Chart",
    "home:dashboardCharts.legendLabel.netWorth": "Net Worth",
    "home:dashboardCharts.legendLabel.assets": "Assests",
    "home:dashboardCharts.legendLabel.liability": "Liabilities",
    "home:guidedOnBoarding.trackAndVisualizeWealth.title": "Monitor Your Wealth And Analyze Your Data",
    "home:guidedOnBoarding.trackAndVisualizeWealth.dashboardView": "Combine all your assets, investments and liabilities in one platform.",
    "home:guidedOnBoarding.trackAndVisualizeWealth.dashboardAllocation": "Explore your asset class, geographical and currency exposure charts to better understand your portfolio diversification.",
    "home:guidedOnBoarding.trackAndVisualizeWealth.assetDetailPage": "Monitor your net worth and the performance of your investments to better plan for your financial goals.",
    "home:guidedOnBoarding.addAndLinkAsset.title": "Add Or Link Your Assets With Ease",
    "home:guidedOnBoarding.addAndLinkAsset.subTitle": "Connect to your financial institutions to get real time updates about your assets and investments.",
    "home:guidedOnBoarding.addAndLinkAsset.assetClass": "We support multiple asset classes and currencies.",
    "home:guidedOnBoarding.addAndLinkAsset.connectInstitutionsIcon": "We connect you to your financial institutions to avoid the hassle of manual updates.",
    "home:guidedOnBoarding.addAndLinkAsset.realTimeUpdate": "We provide real time updates about your assets, investments and liabilities.",
    "home:guidedOnBoarding.securityAndPrivacy.title": "Security and Privacy Come First",
    "home:guidedOnBoarding.securityAndPrivacy.subTitle": "Connect to your financial institutions to get real time updates about your assets and investments.",
    "home:guidedOnBoarding.securityAndPrivacy.highestSecurity": "We use high security encryption to guarantee the safety of your data.",
    "home:guidedOnBoarding.securityAndPrivacy.noAccess": "Our financial advisors and partners cannot access your private information.",
    "home:guidedOnBoarding.securityAndPrivacy.linkAccount": "Connecting your bank accounts to our platform does not reveal your credentials or allow us to make transactions on your behalf. The only purpose of this step is to display your account balance and transactions.",
    "liabilities:page.title": "Liabilities",
    "liabilities:heading": "Liabilities",
    "liabilities:loans.Home": "Home Loans",
    "liabilities:loans.Vehicle": "Vehicle Loans",
    "liabilities:loans.Personal": "Personal Loans",
    "liabilities:loans.Other": "Other Loans",
    "liabilities:label.yourBorrowings": "Your borrowings",
    "liabilities:label.details": "Details",
    "liabilities:label.usd": "USD",
    "liabilities:label.totalMonthylPayment": "Total monthly payment",
    "liabilities:label.upcomingOutflow": "Upcoming outflow",
    "liabilities:label.days": "Days",
    "liabilities:label.lastUpdatedOn": "Last Updated on",
    "liabilities:breadCrumb.wealthOverview": "Wealth Overview",
    "liabilities:breadCrumb.liabilities": "Liabilities",
    "liabilities:table.header.assetName": "Asset name",
    "liabilities:table.header.currentOutstanding": "Current outstanding",
    "liabilities:table.header.monthlyPayment": "  Monthly payment",
    "liabilities:table.header.endDate": "End date",
    "linkAccount:linkAccount.page.title": "Link Account",
    "linkAccount:linkAccount.page.description": "Link your bank account",
    "linkAccount:linkAccount.heading": "Wealth Overview uses TFO to connect your account",
    "linkAccount:linkAccount.card.automatic.title": "Automatically link your accounts",
    "linkAccount:linkAccount.card.automatic.description": " Connect your financial account in seconds to securely and automatically synchronize your balances.",
    "linkAccount:linkAccount.card.manual.title": "Enter manually",
    "linkAccount:linkAccount.card.manual.description": " Quickly add your checking or savings account. TFO will never sell your personal date and only use it with your permission.",
    "linkAccount:linkAccount.button.automatic": "Automatically connect",
    "linkAccount:linkAccount.button.manual": "Enter manually",
    "linkAccount:linkAccount.button.exit": "Exit",
    "linkAccount:linkAccount.text.or": "Or",
    "linkAccount:automaticLink.page.title": "Link Account Automatically",
    "linkAccount:automaticLink.page.description": "Link your bank account automatically",
    "linkAccount:automaticLink.heading": "Add listed asset details",
    "linkAccount:automaticLink.description": "Current account, savings account and term deposit accounts.",
    "linkAccount:automaticLink.card.privacy.title": "Your privacy & data security is our utmost priority",
    "linkAccount:automaticLink.card.privacy.description": " Your credentials are never accessible to any other service. Your data is secured in transit using bank grade TLS 1.2 technology.",
    "linkAccount:automaticLink.button.connect": "Connect",
    "linkAccount:automaticLink.button.exit": "Exit",
    "linkAccount:automaticLink.title": "Link your bank accounts",
    "linkAccount:automaticLink.label.search": "Search for your bank or select an option below",
    "linkAccount:automaticLink.label.popularBank": "Most popular banks",
    "linkAccount:automaticLink.text.notFound": "No bank found",
    "linkAccount:automaticLink.input.bank.placeholder": "Your Bank Name",
    "linkAccount:stepper.heading": "Link your {{bankName}} bank account",
    "linkAccount:stepper.description": "Now you can proceed with linking your bank account following the steps below ",
    "linkAccount:stepper.stepOne.title": "Sign letter of authorization",
    "linkAccount:stepper.stepOne.action.active": "View form and sign letter",
    "linkAccount:stepper.stepOne.action.completed": "View form again",
    "linkAccount:stepper.stepTwo.title": "Share with the bank",
    "linkAccount:stepper.stepTwo.action.active": "Mark as completed",
    "linkAccount:stepper.stepTwo.action.completed": "Completed",
    "linkAccount:stepper.stepThree.title": "Get confirmation from bank via your RM",
    "linkAccount:stepper.label.completed": "Completed",
    "manage:assetDetail.title": "Asset Detail",
    "manage:assetDetail.description": "Asset Description Details",
    "manage:assetDetail.heading": "Home Expense Account",
    "manage:assetDetail.buttons.edit": "Edit Details",
    "manage:assetDetail.buttons.seeMore": "See More",
    "manage:assetDetail.balance": "Balance",
    "manage:assetDetail.netChange": "Net change",
    "manage:assetDetail.last30Days": "Last 30 days",
    "manage:assetDetail.portfolioContribution": "Portfolio contribution",
    "manage:guidedOnBoarding.heading": "Build Your Wealth Dashboard",
    "manage:guidedOnBoarding.steps.selectAsset.title": "Choose an asset or liability",
    "manage:guidedOnBoarding.steps.selectAsset.description": "Build your wealth dashboard by adding all your assets and liabilities.",
    "manage:guidedOnBoarding.steps.firstAsset.title": "Connect to your institutions",
    "manage:guidedOnBoarding.steps.firstAsset.description": "Connect to your financial institutions to monitor your investments in real time.",
    "manage:guidedOnBoarding.steps.viewDashboard.title": "View your wealth dashboard",
    "manage:guidedOnBoarding.steps.viewDashboard.description": "Analyze your data and plan for your financial goals by displaying your wealth details.",
    "profile:changePassword.button.update": "Update",
    "profile:changePassword.button.logout": "Logout",
    "profile:changePassword.validation.heading": "Your password must contain:",
    "profile:changePassword.validation.lowercase": "Lowercase letters (a-z)",
    "profile:changePassword.validation.uppercase": "Uppercase letters (A-Z)",
    "profile:changePassword.validation.numbers": "Numbers (0-9)",
    "profile:changePassword.validation.special": "Special characters (ex.!@#)",
    "profile:changePassword.validation.length": "At least 8 characters",
    "profile:changePassword.validation.confirmPasswordErr": "Passwords do not match.",
    "profile:changePassword.validation.samePasswordsErr": "New password cannot be the same as your old password.",
    "profile:changePassword.label.oldPassword": "Old password",
    "profile:changePassword.label.password": "New password",
    "profile:changePassword.label.confirmPassword": "Confirm new password",
    "profile:changePassword.passwordChanged.heading": "Password Changed",
    "profile:changePassword.passwordChanged.subheading": "You now need to log out and log in again with the new credentials.",
    "profile:changePassword.error.updatePasswordErr": "Wrong password, please try again.",
    "profile:changePassword.placeholder.oldPassword": "Old Password",
    "profile:changePassword.placeholder.newPassword": "New Password",
    "profile:changePassword.placeholder.confirmPassword": "Confirm Password",
    "support:page.title": "Help",
    "support:page.description": "View FAQs and support details",
    "support:heading": "Get support",
    "support:subheading": "Start your global investment journey with no doubts or unclear points.",
    "support:card.talkWithExperts.title": "Talk to our business support team",
    "support:card.talkWithExperts.description": "Request a call at your convenience",
    "support:card.contactClientService.title": "Contact our business support team",
    "support:card.contactClientService.description": "Send a message to our business support team",
    "support:headings.faqs": "FAQs",
    "support:headings.contacts": "Our contacts",
    "support:text.email": "Email",
    "support:modal.getSupport.title": "Get Support",
    "support:modal.getSupport.description": "Start your global investment journey with no doubts or uncertainties.",
    "support:modal.getSupport.contactYou": "Let us contact you",
    "support:modal.getSupport.contactUs": "Or contact us",
    "support:modal.getSupport.yourFinancialAdvisor": "Your financial advisor",
    "support:modal.getSupport.contactFinancialAdvisor": "Speak to your financial advisor",
    "assets:assets.OtherAsset": "Others",
    "common:emptyText.assetClassDescription": "Asset class allocation will appear here once your data is connected.",
    "common:emptyText.mapDescription": "Geographical allocation will appear here once your data is connected.",
    "assetLiabilityForms:heading.otherAssets": "Add other asset",
    "assetLiabilityForms:subHeading.otherAssets": "Uncategorized other investments including vehicles, jewelry and art.",
    "assetLiabilityForms:forms.bankAccount.inputFields.balance.maxValueError": "Amount should be less than 1,000,000,000,000",
    "assetLiabilityForms:forms.bankAccount.inputFields.principal.maxValueError": "Amount should be less than 1,000,000,000,000",
    "assetLiabilityForms:forms.others.inputFields.ownerShip.errorMessageRequired": "Please select ownership",
    "assetLiabilityForms:forms.otherAssets.title": "Fill in your asset details",
    "assets:summary": "Summary",
    "assets:geography.Asia": "Asia",
    "assets:geography.NorthAmerica": "North America",
    "assets:geography.Europe": "Europe",
    "assets:geography.Africa": "Africa",
    "assets:geography.SouthAmerica": "South America",
    "assets:geography.Australia": "Australia",
    "assets:label.valuation": "Valuation",
    "assets:label.keepNetWorth": "To keep your net worth updated, add recent valuation of your asset here.",
    "assets:label.updatedDate": "Date",
    "assets:label.notes": "Note",
    "assets:label.value": "Value",
    "assets:label.note": "note",
    "assets:label.last7Days": "Last 7 days",
    "assets:label.lastDurationDays": "Last {{duration}} days",
    "assets:label.currentBalance": "Current Balance",
    "assets:table.header.assetClass": "Asset Class",
    "assets:charts.last": "Last",
    "assets:charts.days": "days",
    "assets:charts.allocationCharts.legendLabel.listedAsset": "Listed asset",
    "assets:charts.allocationCharts.legendLabel.others": "Others",
    "common:errors.onlyCharactersAllowed": "Only letters are allowed.",
    "common:toast.generic.error.title": "Sorry, something went wrong.",
    "common:button.exit": "Exit",
    "common:formSuccessModal.outstandingBalance": "Outstanding balance",
    "common:formSuccessModal.liabilities.title": "A loan is added to your dashboard",
    "common:emptyText.title": "No data available yet.",
    "common:emptyText.description": "Total Net worth will appear here once your data is connected.",
    "home:custodianBankList.title": "Your banks authorization process",
    "home:custodianBankList.label.bankName": "Bank name",
    "home:custodianBankList.label.status": "Status",
    "home:custodianBankList.label.list": "Bank List",
    "home:custodianBankList.button.view": "View",
    "home:custodianBankList.statusText.signLetter": "Letter signed",
    "home:custodianBankList.statusText.shareWithBank": "Letter signed and shared with the bank",
    "home:custodianBankList.statusText.bankConfirmation": "Received confirmation from the bank",
    "manage:assetAndLiability.assetAndLiabilityList.otherAssets.title": "Others",
    "manage:assetAndLiability.assetAndLiabilityList.otherAssets.description": "Other investments including vehicles, jewelry or pieces of art.",
    "manage:automaticLink.text.notFound": "Not found",
    "profile:tabs.preferences.toast.title": "Preference",
    "profile:tabs.preferences.toast.description": "Firstname and Lastname is updated",
    "profile:tabs.preferences.toast.changePasswordDescription": "Phone number updated"
  };

  var newMap = {};

  for (var item in myObj.keys) {
    var temp = myObj[item];
    item = item.replaceAll(".", "_");
    item = item.replaceAll(":", "_");
    newMap[item] = temp;
  }

  print(jsonEncode(newMap));
}
