// Mocks generated by Mockito 5.3.1 from annotations
// in wmd/test/features/add_assets/add_basic_cash_asset/presentation/manager/bank_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:wmd/core/error_and_success/failures.dart' as _i6;
import 'package:wmd/features/add_assets/add_basic_cash_asset/domain/entities/bank_save_response.dart'
    as _i7;
import 'package:wmd/features/add_assets/add_basic_cash_asset/domain/repositories/bank_repository.dart'
    as _i2;
import 'package:wmd/features/add_assets/add_basic_cash_asset/domain/use_cases/post_bank_details_usecase.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBankRepository_0 extends _i1.SmartFake
    implements _i2.BankRepository {
  _FakeBankRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PostBankDetailsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostBankDetailsUseCase extends _i1.Mock
    implements _i4.PostBankDetailsUseCase {
  MockPostBankDetailsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BankRepository get bankRepository => (super.noSuchMethod(
        Invocation.getter(#bankRepository),
        returnValue: _FakeBankRepository_0(
          this,
          Invocation.getter(#bankRepository),
        ),
      ) as _i2.BankRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.BankSaveResponse>> call(
          Map<String, dynamic>? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i7.BankSaveResponse>>.value(
                _FakeEither_1<_i6.Failure, _i7.BankSaveResponse>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.BankSaveResponse>>);
}
