// Mocks generated by Mockito 5.3.2 from annotations
// in wmd/test/features/add_assets/add_listed_security/presentation/manager/listed_security_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:wmd/core/error_and_success/failures.dart' as _i6;
import 'package:wmd/features/add_assets/add_bank_auto/view_bank_list/domain/entity/bank_entity.dart'
    as _i9;
import 'package:wmd/features/add_assets/add_listed_security/data/models/listed_security_name.dart'
    as _i10;
import 'package:wmd/features/add_assets/add_listed_security/domain/repositories/listed_security_repository.dart'
    as _i2;
import 'package:wmd/features/add_assets/add_listed_security/domain/use_cases/add_listed_security_usecase.dart'
    as _i4;
import 'package:wmd/features/add_assets/add_listed_security/domain/use_cases/get_listed_security_usecase.dart'
    as _i8;
import 'package:wmd/features/add_assets/core/domain/entities/add_asset_response.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeListedSecurityRepository_0 extends _i1.SmartFake
    implements _i2.ListedSecurityRepository {
  _FakeListedSecurityRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AddListedSecurityUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddListedSecurityUseCase extends _i1.Mock
    implements _i4.AddListedSecurityUseCase {
  MockAddListedSecurityUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ListedSecurityRepository get listedSecurityRepository =>
      (super.noSuchMethod(
        Invocation.getter(#listedSecurityRepository),
        returnValue: _FakeListedSecurityRepository_0(
          this,
          Invocation.getter(#listedSecurityRepository),
        ),
      ) as _i2.ListedSecurityRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.AddAsset>> call(
          Map<String, dynamic>? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.AddAsset>>.value(
            _FakeEither_1<_i6.Failure, _i7.AddAsset>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.AddAsset>>);
}

/// A class which mocks [GetListedSecurityUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetListedSecurityUseCase extends _i1.Mock
    implements _i8.GetListedSecurityUseCase {
  MockGetListedSecurityUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ListedSecurityRepository get listedSecurityRepository =>
      (super.noSuchMethod(
        Invocation.getter(#listedSecurityRepository),
        returnValue: _FakeListedSecurityRepository_0(
          this,
          Invocation.getter(#listedSecurityRepository),
        ),
      ) as _i2.ListedSecurityRepository);
  @override
  set banks(List<_i9.BankEntity>? _banks) => super.noSuchMethod(
        Invocation.setter(
          #banks,
          _banks,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i10.ListedSecurityName>>> call(
          String? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<
                _i3.Either<_i6.Failure, List<_i10.ListedSecurityName>>>.value(
            _FakeEither_1<_i6.Failure, List<_i10.ListedSecurityName>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i10.ListedSecurityName>>>);
}
