// Mocks generated by Mockito 5.3.1 from annotations
// in wmd/test/features/add_assets/custodian_bank_auth/domain/use_cases/get_custodian_bank_list_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:wmd/core/error_and_success/failures.dart' as _i5;
import 'package:wmd/features/add_assets/custodian_bank_auth/data/models/get_custodian_bank_list_params.dart'
    as _i7;
import 'package:wmd/features/add_assets/custodian_bank_auth/data/models/get_custodian_bank_status_params.dart'
    as _i11;
import 'package:wmd/features/add_assets/custodian_bank_auth/data/models/post_custodian_bank_status_params.dart'
    as _i9;
import 'package:wmd/features/add_assets/custodian_bank_auth/domain/entities/custodian_bank_entity.dart'
    as _i6;
import 'package:wmd/features/add_assets/custodian_bank_auth/domain/entities/get_custodian_bank_status_entity.dart'
    as _i10;
import 'package:wmd/features/add_assets/custodian_bank_auth/domain/entities/post_custodian_bank_status_entity.dart'
    as _i8;
import 'package:wmd/features/add_assets/custodian_bank_auth/domain/repositories/custodian_bank_auth_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CustodianBankAuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCustodianBankAuthRepository extends _i1.Mock
    implements _i3.CustodianBankAuthRepository {
  MockCustodianBankAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.CustodianBankEntity>>>
      getCustodianBankList(_i7.GetCustodianBankListParams? params) =>
          (super.noSuchMethod(
            Invocation.method(
              #getCustodianBankList,
              [params],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure,
                        List<_i6.CustodianBankEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.CustodianBankEntity>>(
              this,
              Invocation.method(
                #getCustodianBankList,
                [params],
              ),
            )),
          ) as _i4
              .Future<_i2.Either<_i5.Failure, List<_i6.CustodianBankEntity>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.PostCustodianBankStatusEntity>>
      postCustodianBankStatus(_i9.PostCustodianBankStatusParams? params) =>
          (super.noSuchMethod(
            Invocation.method(
              #postCustodianBankStatus,
              [params],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure,
                        _i8.PostCustodianBankStatusEntity>>.value(
                _FakeEither_0<_i5.Failure, _i8.PostCustodianBankStatusEntity>(
              this,
              Invocation.method(
                #postCustodianBankStatus,
                [params],
              ),
            )),
          ) as _i4.Future<
              _i2.Either<_i5.Failure, _i8.PostCustodianBankStatusEntity>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i10.CustodianBankStatusEntity>>
      getCustodianBankStatus(_i11.GetCustodianBankStatusParams? params) =>
          (super.noSuchMethod(
            Invocation.method(
              #getCustodianBankStatus,
              [params],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure,
                        _i10.CustodianBankStatusEntity>>.value(
                _FakeEither_0<_i5.Failure, _i10.CustodianBankStatusEntity>(
              this,
              Invocation.method(
                #getCustodianBankStatus,
                [params],
              ),
            )),
          ) as _i4
              .Future<_i2.Either<_i5.Failure, _i10.CustodianBankStatusEntity>>);
}
