// Mocks generated by Mockito 5.3.1 from annotations
// in wmd/test/core/data/network/error_handler_middleware_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:wmd/core/data/network/error_handler_middleware.dart' as _i6;
import 'package:wmd/core/data/network/server_request_manager.dart' as _i3;
import 'package:wmd/core/models/app_request_options.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_1<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeServerRequestManager_2 extends _i1.SmartFake
    implements _i3.ServerRequestManager {
  _FakeServerRequestManager_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ServerRequestManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockServerRequestManager extends _i1.Mock
    implements _i3.ServerRequestManager {
  MockServerRequestManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_0(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i2.Dio);
  @override
  _i4.Future<_i2.Response<dynamic>> sendRequest(
          _i5.AppRequestOptions? appRequestOptions) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendRequest,
          [appRequestOptions],
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #sendRequest,
            [appRequestOptions],
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);
}

/// A class which mocks [ErrorHandlerMiddleware].
///
/// See the documentation for Mockito's code generation for more information.
class MockErrorHandlerMiddleware extends _i1.Mock
    implements _i6.ErrorHandlerMiddleware {
  MockErrorHandlerMiddleware() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.ServerRequestManager get serverRequestManager => (super.noSuchMethod(
        Invocation.getter(#serverRequestManager),
        returnValue: _FakeServerRequestManager_2(
          this,
          Invocation.getter(#serverRequestManager),
        ),
      ) as _i3.ServerRequestManager);
  @override
  _i4.Future<dynamic> sendRequest(_i5.AppRequestOptions? appRequestOptions) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendRequest,
          [appRequestOptions],
        ),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);
}
