// Mocks generated by Mockito 5.3.1 from annotations
// in wmd/test/features/help/faq/data/repositories/faq_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:wmd/core/domain/usecases/usercase.dart' as _i6;
import 'package:wmd/core/error_and_success/failures.dart' as _i8;
import 'package:wmd/features/help/faq/data/data_sources/faq_remote_data_source.dart'
    as _i3;
import 'package:wmd/features/help/faq/data/models/faq.dart' as _i5;
import 'package:wmd/features/help/faq/domain/repositories/faq_repository.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FaqRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFaqRemoteDataSource extends _i1.Mock
    implements _i3.FaqRemoteDataSource {
  MockFaqRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.Faq>> getFAQs(_i6.NoParams? noParams) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFAQs,
          [noParams],
        ),
        returnValue: _i4.Future<List<_i5.Faq>>.value(<_i5.Faq>[]),
      ) as _i4.Future<List<_i5.Faq>>);
}

/// A class which mocks [FaqRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFaqRepository extends _i1.Mock implements _i7.FaqRepository {
  MockFaqRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i8.Failure, List<_i5.Faq>>> getFAQs(
          _i6.NoParams? noParams) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFAQs,
          [noParams],
        ),
        returnValue: _i4.Future<_i2.Either<_i8.Failure, List<_i5.Faq>>>.value(
            _FakeEither_0<_i8.Failure, List<_i5.Faq>>(
          this,
          Invocation.method(
            #getFAQs,
            [noParams],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i8.Failure, List<_i5.Faq>>>);
}
