// Mocks generated by Mockito 5.3.2 from annotations
// in wmd/test/features/edit_assets/edit_private_debt/data/repositories/edit_private_debt_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dartz/dartz.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:wmd/core/error_and_success/failures.dart' as _i10;
import 'package:wmd/core/error_and_success/succeses.dart' as _i11;
import 'package:wmd/features/edit_assets/edit_private_debt/data/data_sources/edit_private_debt_remote_datasource.dart'
    as _i5;
import 'package:wmd/features/edit_assets/edit_private_debt/data/models/delete_private_debt_params.dart'
    as _i8;
import 'package:wmd/features/edit_assets/edit_private_debt/data/models/delete_private_debt_response.dart'
    as _i3;
import 'package:wmd/features/edit_assets/edit_private_debt/data/models/put_private_debt_params.dart'
    as _i7;
import 'package:wmd/features/edit_assets/edit_private_debt/data/models/put_private_debt_response.dart'
    as _i2;
import 'package:wmd/features/edit_assets/edit_private_debt/domain/repositories/edit_private_debt_repository.dart'
    as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePutPrivateDebtResponse_0 extends _i1.SmartFake
    implements _i2.PutPrivateDebtResponse {
  _FakePutPrivateDebtResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeletePrivateDebtResponse_1 extends _i1.SmartFake
    implements _i3.DeletePrivateDebtResponse {
  _FakeDeletePrivateDebtResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_2<L, R> extends _i1.SmartFake implements _i4.Either<L, R> {
  _FakeEither_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [EditPrivateDebtRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockEditPrivateDebtRemoteDataSource extends _i1.Mock
    implements _i5.EditPrivateDebtRemoteDataSource {
  MockEditPrivateDebtRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.PutPrivateDebtResponse> putPrivateDebt(
          _i7.PutPrivateDebtParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #putPrivateDebt,
          [params],
        ),
        returnValue: _i6.Future<_i2.PutPrivateDebtResponse>.value(
            _FakePutPrivateDebtResponse_0(
          this,
          Invocation.method(
            #putPrivateDebt,
            [params],
          ),
        )),
      ) as _i6.Future<_i2.PutPrivateDebtResponse>);
  @override
  _i6.Future<_i3.DeletePrivateDebtResponse> deletePrivateDebt(
          _i8.DeletePrivateDebtParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePrivateDebt,
          [params],
        ),
        returnValue: _i6.Future<_i3.DeletePrivateDebtResponse>.value(
            _FakeDeletePrivateDebtResponse_1(
          this,
          Invocation.method(
            #deletePrivateDebt,
            [params],
          ),
        )),
      ) as _i6.Future<_i3.DeletePrivateDebtResponse>);
}

/// A class which mocks [EditPrivateDebtRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockEditPrivateDebtRepository extends _i1.Mock
    implements _i9.EditPrivateDebtRepository {
  MockEditPrivateDebtRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.Either<_i10.Failure, _i11.AppSuccess>> putPrivateDebt(
          _i7.PutPrivateDebtParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #putPrivateDebt,
          [params],
        ),
        returnValue:
            _i6.Future<_i4.Either<_i10.Failure, _i11.AppSuccess>>.value(
                _FakeEither_2<_i10.Failure, _i11.AppSuccess>(
          this,
          Invocation.method(
            #putPrivateDebt,
            [params],
          ),
        )),
      ) as _i6.Future<_i4.Either<_i10.Failure, _i11.AppSuccess>>);
  @override
  _i6.Future<_i4.Either<_i10.Failure, _i11.AppSuccess>> deletePrivateDebt(
          _i8.DeletePrivateDebtParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePrivateDebt,
          [params],
        ),
        returnValue:
            _i6.Future<_i4.Either<_i10.Failure, _i11.AppSuccess>>.value(
                _FakeEither_2<_i10.Failure, _i11.AppSuccess>(
          this,
          Invocation.method(
            #deletePrivateDebt,
            [params],
          ),
        )),
      ) as _i6.Future<_i4.Either<_i10.Failure, _i11.AppSuccess>>);
}
